import { err, ok } from '@device-manager-ui/services/shared/serviceResult'
import type {
  ProjectArea,
  ProjectAreaAdapter,
  ProjectAreaGeometry,
  ProjectAreaPlanMode,
  ProjectAreaSettings,
  ProjectFloorPlan,
  ProjectFloorPlanSourceReference,
} from '../../types'
import { createProjectAreaWhiteModelExtractionRuntime } from '../white-model-extraction/projectAreaWhiteModelExtraction'

type ProjectAreaSeed = Omit<ProjectArea, 'planMode'> & {
  planMode?: ProjectAreaPlanMode
}

const AREAS: ProjectAreaSeed[] = [
  {
    id: 'area-dream-city',
    projectId: 'doraemon',
    name: '梦想之城',
    type: 'site',
    code: 'DC-ROOT',
    aliases: ['城市级项目', '总空间'],
    sortOrder: 10,
    description: '城市级项目根空间，承载商业、能源、工业、康养和科技园区等空间结构。',
    planMode: 'own',
  },
  {
    id: 'area-mall',
    projectId: 'doraemon',
    parentId: 'area-dream-city',
    name: '星环购物中心',
    type: 'building',
    code: 'DC-MALL',
    aliases: ['大型商场', '商业综合体'],
    sortOrder: 20,
    description: '大型商业综合体，包含中庭、主力店、餐饮影院和地下停车区域。',
    planMode: 'own',
  },
  {
    id: 'area-mall-1f',
    projectId: 'doraemon',
    parentId: 'area-mall',
    name: '1F 中庭层',
    type: 'floor',
    code: 'DC-MALL-1F',
    aliases: ['首层', '中庭层'],
    sortOrder: 30,
    description: '购物中心首层客流最密集区域，包含中庭、主力店和服务台。',
    planMode: 'own',
    floorPlanId: 'plan-mall-1f',
  },
  {
    id: 'area-mall-atrium',
    projectId: 'doraemon',
    parentId: 'area-mall-1f',
    name: '中央中庭',
    type: 'zone',
    code: 'DC-MALL-ATRIUM',
    aliases: ['中庭', '活动区'],
    sortOrder: 40,
    description: '品牌活动、客流汇聚和跨层可视的核心公共空间。',
  },
  {
    id: 'area-mall-anchor',
    projectId: 'doraemon',
    parentId: 'area-mall-1f',
    name: '主力店区',
    type: 'zone',
    code: 'DC-MALL-ANCHOR',
    aliases: ['主力店', '零售区'],
    sortOrder: 50,
    description: '大面积零售门店集中区域，用于承接稳定客流和巡场路线。',
  },
  {
    id: 'area-mall-service-desk',
    projectId: 'doraemon',
    parentId: 'area-mall-1f',
    name: '服务台',
    type: 'room',
    code: 'DC-MALL-SERVICE',
    aliases: ['客服台', '问询台'],
    sortOrder: 60,
    description: '顾客咨询、失物登记和运营人员交接区域。',
  },
  {
    id: 'area-mall-fire-passage',
    projectId: 'doraemon',
    parentId: 'area-mall-1f',
    name: '消防通道',
    type: 'zone',
    code: 'DC-MALL-FIRE-PASSAGE',
    aliases: ['疏散通道'],
    sortOrder: 70,
    description: '首层主要疏散动线，只维护空间边界，不维护消防设备。',
  },
  {
    id: 'area-mall-b1',
    projectId: 'doraemon',
    parentId: 'area-mall',
    name: 'B1 停车层',
    type: 'floor',
    code: 'DC-MALL-B1',
    aliases: ['地下停车场'],
    sortOrder: 80,
    description: '地下车辆停放、装卸补货和机电用房所在楼层。',
    planMode: 'own',
    floorPlanId: 'plan-mall-b1',
  },
  {
    id: 'area-mall-parking-east',
    projectId: 'doraemon',
    parentId: 'area-mall-b1',
    name: '东侧车库',
    type: 'zone',
    code: 'DC-MALL-PARK-E',
    aliases: ['东区停车场'],
    sortOrder: 90,
    description: '靠近主入口的地下停车区域，供车辆流线引用。',
  },
  {
    id: 'area-mall-loading',
    projectId: 'doraemon',
    parentId: 'area-mall-b1',
    name: '卸货通道',
    type: 'zone',
    code: 'DC-MALL-LOADING',
    aliases: ['后勤通道'],
    sortOrder: 100,
    description: '商户补货和后勤车辆通行空间。',
  },
  {
    id: 'area-fuel-station',
    projectId: 'doraemon',
    parentId: 'area-dream-city',
    name: '晨光能源站',
    type: 'zone',
    code: 'DC-FUEL',
    aliases: ['加油站', '能源补给站'],
    sortOrder: 120,
    description: '面向城市车辆的能源补给区域，包含站房、加油作业区和卸油安全区。',
    planMode: 'own',
    floorPlanId: 'plan-fuel-site',
  },
  {
    id: 'area-fuel-building',
    projectId: 'doraemon',
    parentId: 'area-fuel-station',
    name: '站房',
    type: 'building',
    code: 'DC-FUEL-BLD',
    aliases: ['营业站房'],
    sortOrder: 130,
    description: '能源站营业、值守和小型便利服务所在建筑。',
  },
  {
    id: 'area-fuel-building-1f',
    projectId: 'doraemon',
    parentId: 'area-fuel-building',
    name: '1F 营业层',
    type: 'floor',
    code: 'DC-FUEL-1F',
    aliases: ['站房一层'],
    sortOrder: 140,
    description: '站房首层营业空间，包含便利店、收银和员工值守区域。',
    planMode: 'own',
    floorPlanId: 'plan-fuel-building-1f',
  },
  {
    id: 'area-fuel-store',
    projectId: 'doraemon',
    parentId: 'area-fuel-building-1f',
    name: '便利店',
    type: 'zone',
    code: 'DC-FUEL-STORE',
    aliases: ['站内便利店'],
    sortOrder: 150,
    description: '顾客短暂停留和非油品消费区域。',
  },
  {
    id: 'area-fuel-cashier',
    projectId: 'doraemon',
    parentId: 'area-fuel-building-1f',
    name: '收银区',
    type: 'room',
    code: 'DC-FUEL-CASHIER',
    aliases: ['前台'],
    sortOrder: 160,
    description: '支付、开票和班组交接区域。',
  },
  {
    id: 'area-fuel-duty',
    projectId: 'doraemon',
    parentId: 'area-fuel-building-1f',
    name: '值班室',
    type: 'room',
    code: 'DC-FUEL-DUTY',
    aliases: ['站长室'],
    sortOrder: 170,
    description: '站内人员值守、交接和资料存放空间。',
  },
  {
    id: 'area-fuel-canopy',
    projectId: 'doraemon',
    parentId: 'area-fuel-station',
    name: '加油作业区',
    type: 'zone',
    code: 'DC-FUEL-CANOPY',
    aliases: ['罩棚区'],
    sortOrder: 180,
    description: '车辆加油、排队和人员短暂停留的核心室外区域。',
  },
  {
    id: 'area-fuel-island-1',
    projectId: 'doraemon',
    parentId: 'area-fuel-canopy',
    name: '1号加油岛',
    type: 'point',
    code: 'DC-FUEL-ISLAND-1',
    aliases: ['一号岛'],
    sortOrder: 190,
    description: '罩棚下的独立加油岛点位，用于模块引用空间位置。',
  },
  {
    id: 'area-fuel-unloading',
    projectId: 'doraemon',
    parentId: 'area-fuel-station',
    name: '卸油区',
    type: 'zone',
    code: 'DC-FUEL-UNLOAD',
    aliases: ['油罐卸油区'],
    sortOrder: 200,
    description: '油品卸载和安全隔离范围。',
  },
  {
    id: 'area-chem-plant',
    projectId: 'doraemon',
    parentId: 'area-dream-city',
    name: '青岚化工厂',
    type: 'zone',
    code: 'DC-CHEM',
    aliases: ['化工厂', '工业厂区'],
    sortOrder: 220,
    description: '化工生产与储运厂区，包含中控、装置、罐区和装卸区域。',
    planMode: 'own',
  },
  {
    id: 'area-chem-control-building',
    projectId: 'doraemon',
    parentId: 'area-chem-plant',
    name: '中控楼',
    type: 'building',
    code: 'DC-CHEM-CTRL',
    aliases: ['控制楼'],
    sortOrder: 230,
    description: '生产调度、工艺监控和班组值守所在建筑。',
  },
  {
    id: 'area-chem-control-1f',
    projectId: 'doraemon',
    parentId: 'area-chem-control-building',
    name: '1F 控制层',
    type: 'floor',
    code: 'DC-CHEM-CTRL-1F',
    aliases: ['控制室层'],
    sortOrder: 240,
    description: '中控大厅、交接班和应急联络所在楼层。',
    planMode: 'own',
    floorPlanId: 'plan-chem-control-1f',
  },
  {
    id: 'area-chem-control-room',
    projectId: 'doraemon',
    parentId: 'area-chem-control-1f',
    name: '中控大厅',
    type: 'room',
    code: 'DC-CHEM-CTRL-ROOM',
    aliases: ['控制大厅'],
    sortOrder: 250,
    description: '厂区运行监控和调度指挥空间。',
  },
  {
    id: 'area-chem-shift-room',
    projectId: 'doraemon',
    parentId: 'area-chem-control-1f',
    name: '交接班室',
    type: 'room',
    code: 'DC-CHEM-SHIFT',
    aliases: ['班组室'],
    sortOrder: 260,
    description: '班组交接、巡检记录确认和临时会议空间。',
  },
  {
    id: 'area-chem-process',
    projectId: 'doraemon',
    parentId: 'area-chem-plant',
    name: '联合装置区',
    type: 'zone',
    code: 'DC-CHEM-PROCESS',
    aliases: ['生产装置区'],
    sortOrder: 270,
    description: '主要生产工艺装置所在区域。',
  },
  {
    id: 'area-chem-reactor',
    projectId: 'doraemon',
    parentId: 'area-chem-process',
    name: '反应车间',
    type: 'building',
    code: 'DC-CHEM-REACTOR',
    aliases: ['反应单元'],
    sortOrder: 280,
    description: '反应釜、投料和巡检通道所在建筑。',
  },
  {
    id: 'area-chem-reactor-1f',
    projectId: 'doraemon',
    parentId: 'area-chem-reactor',
    name: '1F 工艺层',
    type: 'floor',
    code: 'DC-CHEM-REACTOR-1F',
    aliases: ['工艺层'],
    sortOrder: 290,
    description: '反应工艺、投料和现场巡检主要楼层。',
    planMode: 'own',
    floorPlanId: 'plan-chem-process',
  },
  {
    id: 'area-chem-kettle',
    projectId: 'doraemon',
    parentId: 'area-chem-reactor-1f',
    name: '反应釜区',
    type: 'zone',
    code: 'DC-CHEM-KETTLE',
    aliases: ['釜区'],
    sortOrder: 300,
    description: '反应釜集中布置空间，供工艺和告警模块引用。',
  },
  {
    id: 'area-chem-feeding',
    projectId: 'doraemon',
    parentId: 'area-chem-reactor-1f',
    name: '投料间',
    type: 'room',
    code: 'DC-CHEM-FEED',
    aliases: ['投料室'],
    sortOrder: 310,
    description: '原料投放和短时操作空间。',
  },
  {
    id: 'area-chem-tank-farm',
    projectId: 'doraemon',
    parentId: 'area-chem-plant',
    name: '储罐区',
    type: 'zone',
    code: 'DC-CHEM-TANK',
    aliases: ['罐区'],
    sortOrder: 320,
    description: '物料储罐和围堰空间。',
    planMode: 'own',
    floorPlanId: 'plan-chem-tank',
  },
  {
    id: 'area-chem-loading',
    projectId: 'doraemon',
    parentId: 'area-chem-tank-farm',
    name: '装卸栈台',
    type: 'zone',
    code: 'DC-CHEM-LOADING',
    aliases: ['装卸区'],
    sortOrder: 330,
    description: '槽车装卸和车辆等待空间。',
  },
  {
    id: 'area-care-home',
    projectId: 'doraemon',
    parentId: 'area-dream-city',
    name: '松龄颐养院',
    type: 'zone',
    code: 'DC-CARE',
    aliases: ['养老院', '康养院'],
    sortOrder: 350,
    description: '面向老人照护、康复活动和院区生活服务的复合空间。',
    planMode: 'own',
  },
  {
    id: 'area-care-building',
    projectId: 'doraemon',
    parentId: 'area-care-home',
    name: '康养楼',
    type: 'building',
    code: 'DC-CARE-BLD',
    aliases: ['照护楼'],
    sortOrder: 360,
    description: '老人日常照护、公共服务和护理站所在建筑。',
  },
  {
    id: 'area-care-1f',
    projectId: 'doraemon',
    parentId: 'area-care-building',
    name: '1F 公共服务层',
    type: 'floor',
    code: 'DC-CARE-1F',
    aliases: ['首层服务区'],
    sortOrder: 370,
    description: '接待、护理站、公共活动和家属探访所在楼层。',
    planMode: 'own',
    floorPlanId: 'plan-care-1f',
  },
  {
    id: 'area-care-lobby',
    projectId: 'doraemon',
    parentId: 'area-care-1f',
    name: '接待大厅',
    type: 'zone',
    code: 'DC-CARE-LOBBY',
    aliases: ['大厅'],
    sortOrder: 380,
    description: '家属接待、访客登记和老人出入院流线空间。',
  },
  {
    id: 'area-care-nurse',
    projectId: 'doraemon',
    parentId: 'area-care-1f',
    name: '护理站',
    type: 'room',
    code: 'DC-CARE-NURSE',
    aliases: ['护士站'],
    sortOrder: 390,
    description: '护理人员值守和日常照护响应空间。',
  },
  {
    id: 'area-care-activity',
    projectId: 'doraemon',
    parentId: 'area-care-1f',
    name: '活动室',
    type: 'room',
    code: 'DC-CARE-ACTIVITY',
    aliases: ['文娱室'],
    sortOrder: 400,
    description: '老人日间活动、课程和集体休闲空间。',
  },
  {
    id: 'area-care-3f',
    projectId: 'doraemon',
    parentId: 'area-care-building',
    name: '3F 生活照护层',
    type: 'floor',
    code: 'DC-CARE-3F',
    aliases: ['三层住区'],
    sortOrder: 410,
    description: '老人居住、夜间巡视和护理照护所在楼层。',
    planMode: 'own',
    floorPlanId: 'plan-care-3f',
  },
  {
    id: 'area-care-east-ward',
    projectId: 'doraemon',
    parentId: 'area-care-3f',
    name: '东侧住区',
    type: 'zone',
    code: 'DC-CARE-EAST',
    aliases: ['东区房间'],
    sortOrder: 420,
    description: '东侧居住房间和公共走廊区域。',
  },
  {
    id: 'area-care-garden',
    projectId: 'doraemon',
    parentId: 'area-care-home',
    name: '康复花园',
    type: 'zone',
    code: 'DC-CARE-GARDEN',
    aliases: ['花园', '步道'],
    sortOrder: 430,
    description: '老人户外康复、散步和家属陪伴区域。',
    planMode: 'own',
  },
  {
    id: 'area-tech-park',
    projectId: 'doraemon',
    parentId: 'area-dream-city',
    name: '云栖科创园',
    type: 'zone',
    code: 'DC-TECH',
    aliases: ['科技园区', '科创园'],
    sortOrder: 450,
    description: '研发办公、数据中心、访客服务和园区出入口组合空间。',
    planMode: 'own',
  },
  {
    id: 'area-tech-rd-building',
    projectId: 'doraemon',
    parentId: 'area-tech-park',
    name: 'A座研发楼',
    type: 'building',
    code: 'DC-TECH-A',
    aliases: ['研发楼A座'],
    sortOrder: 460,
    description: '研发团队办公、实验和会议所在建筑。',
  },
  {
    id: 'area-tech-rd-2f',
    projectId: 'doraemon',
    parentId: 'area-tech-rd-building',
    name: '2F 研发办公层',
    type: 'floor',
    code: 'DC-TECH-A-2F',
    aliases: ['二层办公'],
    sortOrder: 470,
    description: '开放办公、实验室和会议空间所在楼层。',
    planMode: 'own',
    floorPlanId: 'plan-tech-rd-2f',
  },
  {
    id: 'area-tech-open-office',
    projectId: 'doraemon',
    parentId: 'area-tech-rd-2f',
    name: '开放办公区',
    type: 'zone',
    code: 'DC-TECH-OFFICE',
    aliases: ['办公区'],
    sortOrder: 480,
    description: '研发团队日常办公和协作区域。',
  },
  {
    id: 'area-tech-lab',
    projectId: 'doraemon',
    parentId: 'area-tech-rd-2f',
    name: '联合实验室',
    type: 'room',
    code: 'DC-TECH-LAB',
    aliases: ['实验室'],
    sortOrder: 490,
    description: '产品验证、设备联调和样机测试空间。',
  },
  {
    id: 'area-tech-meeting',
    projectId: 'doraemon',
    parentId: 'area-tech-rd-2f',
    name: '会议区',
    type: 'zone',
    code: 'DC-TECH-MEETING',
    aliases: ['会议室组'],
    sortOrder: 500,
    description: '团队会议、客户交流和项目评审空间。',
  },
  {
    id: 'area-tech-dc-building',
    projectId: 'doraemon',
    parentId: 'area-tech-park',
    name: '数据中心',
    type: 'building',
    code: 'DC-TECH-IDC',
    aliases: ['IDC'],
    sortOrder: 510,
    description: '园区算力和核心机房所在建筑。',
  },
  {
    id: 'area-tech-dc-1f',
    projectId: 'doraemon',
    parentId: 'area-tech-dc-building',
    name: '1F 机房层',
    type: 'floor',
    code: 'DC-TECH-IDC-1F',
    aliases: ['机房一层'],
    sortOrder: 520,
    description: '主机房、供电和制冷通道所在楼层。',
    planMode: 'own',
    floorPlanId: 'plan-tech-dc-1f',
  },
  {
    id: 'area-tech-server-room',
    projectId: 'doraemon',
    parentId: 'area-tech-dc-1f',
    name: '主机房',
    type: 'zone',
    code: 'DC-TECH-SERVER',
    aliases: ['服务器机房'],
    sortOrder: 530,
    description: '服务器机柜和核心网络设备所在空间。',
  },
  {
    id: 'area-tech-ups',
    projectId: 'doraemon',
    parentId: 'area-tech-dc-1f',
    name: 'UPS间',
    type: 'room',
    code: 'DC-TECH-UPS',
    aliases: ['供电间'],
    sortOrder: 540,
    description: '不间断电源和配电支撑空间。',
  },
  {
    id: 'area-tech-north-gate',
    projectId: 'doraemon',
    parentId: 'area-tech-park',
    name: '北门访客区',
    type: 'zone',
    code: 'DC-TECH-GATE-N',
    aliases: ['北门', '访客入口'],
    sortOrder: 550,
    description: '访客登记、车辆出入和园区形象入口空间。',
  },
]

let areaState: ProjectArea[] = AREAS.map(normalizeArea).map(cloneArea)

const MALL_FLOOR_PLAN_REFERENCE: ProjectFloorPlanSourceReference = {
  name: 'LaLaport EBINA 1F 官方楼层平面图',
  url: 'https://mitsui-shopping-park.com/lalaport/ebina/floor/floorMap_1f.pdf',
  previewImageUrl: '/images/floorplans/lalaport-ebina-1f-floorMap.png',
  publisher: 'Mitsui Fudosan Retail Management Co., Ltd.',
  note: '星环购物中心为演示项目名；当前使用真实商场 LaLaport EBINA 官方 1F 平面图作为白模生成参考源，原型白模由本地生成资产承载。',
}

const FLOOR_PLANS: ProjectFloorPlan[] = [
  {
    id: 'plan-mall-1f',
    projectId: 'doraemon',
    areaId: 'area-mall-1f',
    name: '星环购物中心 1F 平面图',
    fileName: 'lalaport-ebina-1f-floorMap.pdf',
    fileType: 'pdf',
    scale: '官方导览图',
    rotation: '官网原图',
    status: 'ready',
    updatedAt: '2026-05-03',
    sourceReference: MALL_FLOOR_PLAN_REFERENCE,
  },
  {
    id: 'plan-mall-b1',
    projectId: 'doraemon',
    areaId: 'area-mall-b1',
    name: '星环购物中心 B1 平面图',
    fileName: 'dream-city-mall-b1.svg',
    fileType: 'svg',
    scale: '1:350',
    rotation: '车道入口朝东',
    status: 'draft',
    updatedAt: '2026-05-03',
  },
  {
    id: 'plan-fuel-site',
    projectId: 'doraemon',
    areaId: 'area-fuel-station',
    name: '晨光能源站总平面图',
    fileName: 'dream-city-fuel-site.svg',
    fileType: 'svg',
    scale: '1:500',
    rotation: '车行入口朝南',
    status: 'ready',
    updatedAt: '2026-05-03',
  },
  {
    id: 'plan-fuel-building-1f',
    projectId: 'doraemon',
    areaId: 'area-fuel-building-1f',
    name: '晨光能源站站房 1F 平面图',
    fileName: 'dream-city-fuel-building-1f.svg',
    fileType: 'svg',
    scale: '1:120',
    rotation: '北向上',
    status: 'ready',
    updatedAt: '2026-05-03',
  },
  {
    id: 'plan-chem-control-1f',
    projectId: 'doraemon',
    areaId: 'area-chem-control-1f',
    name: '青岚化工厂中控楼 1F 平面图',
    fileName: 'dream-city-chem-control-1f.svg',
    fileType: 'svg',
    scale: '1:180',
    rotation: '主入口朝西',
    status: 'ready',
    updatedAt: '2026-05-03',
  },
  {
    id: 'plan-chem-process',
    projectId: 'doraemon',
    areaId: 'area-chem-reactor-1f',
    name: '青岚化工厂反应车间 1F 平面图',
    fileName: 'dream-city-chem-process.svg',
    fileType: 'svg',
    scale: '1:260',
    rotation: '工艺管廊南北向',
    status: 'ready',
    updatedAt: '2026-05-03',
  },
  {
    id: 'plan-chem-tank',
    projectId: 'doraemon',
    areaId: 'area-chem-tank-farm',
    name: '青岚化工厂罐区平面图',
    fileName: 'dream-city-chem-tank.svg',
    fileType: 'svg',
    scale: '1:600',
    rotation: '装卸口朝东',
    status: 'draft',
    updatedAt: '2026-05-03',
  },
  {
    id: 'plan-care-1f',
    projectId: 'doraemon',
    areaId: 'area-care-1f',
    name: '松龄颐养院 1F 平面图',
    fileName: 'dream-city-care-1f.svg',
    fileType: 'svg',
    scale: '1:180',
    rotation: '主入口朝南',
    status: 'ready',
    updatedAt: '2026-05-03',
  },
  {
    id: 'plan-care-3f',
    projectId: 'doraemon',
    areaId: 'area-care-3f',
    name: '松龄颐养院 3F 平面图',
    fileName: 'dream-city-care-3f.svg',
    fileType: 'svg',
    scale: '1:180',
    rotation: '护理站居中',
    status: 'draft',
    updatedAt: '2026-05-03',
  },
  {
    id: 'plan-tech-rd-2f',
    projectId: 'doraemon',
    areaId: 'area-tech-rd-2f',
    name: '云栖科创园 A座 2F 平面图',
    fileName: 'dream-city-tech-a-2f.svg',
    fileType: 'svg',
    scale: '1:220',
    rotation: '电梯厅朝西',
    status: 'ready',
    updatedAt: '2026-05-03',
  },
  {
    id: 'plan-tech-dc-1f',
    projectId: 'doraemon',
    areaId: 'area-tech-dc-1f',
    name: '云栖科创园数据中心 1F 平面图',
    fileName: 'dream-city-tech-idc-1f.svg',
    fileType: 'svg',
    scale: '1:160',
    rotation: '冷通道东西向',
    status: 'ready',
    updatedAt: '2026-05-03',
  },
]

const whiteModelExtractionRuntime = createProjectAreaWhiteModelExtractionRuntime({
  floorPlans: FLOOR_PLANS,
  seedPublishedFloorPlanIds: ['plan-mall-1f'],
})

const GEOMETRIES: ProjectAreaGeometry[] = [
  {
    id: 'geo-mall-atrium',
    projectId: 'doraemon',
    floorPlanId: 'plan-mall-1f',
    areaId: 'area-mall-atrium',
    x: 8,
    y: 14,
    width: 48,
    height: 42,
    labelX: 30,
    labelY: 36,
  },
  {
    id: 'geo-mall-service',
    projectId: 'doraemon',
    floorPlanId: 'plan-mall-1f',
    areaId: 'area-mall-service-desk',
    x: 10,
    y: 58,
    width: 26,
    height: 22,
    labelX: 22,
    labelY: 70,
  },
  {
    id: 'geo-mall-anchor',
    projectId: 'doraemon',
    floorPlanId: 'plan-mall-1f',
    areaId: 'area-mall-anchor',
    x: 60,
    y: 14,
    width: 30,
    height: 30,
    labelX: 74,
    labelY: 30,
  },
  {
    id: 'geo-mall-fire-passage',
    projectId: 'doraemon',
    floorPlanId: 'plan-mall-1f',
    areaId: 'area-mall-fire-passage',
    x: 60,
    y: 48,
    width: 30,
    height: 32,
    labelX: 74,
    labelY: 65,
  },
  {
    id: 'geo-mall-parking-east',
    projectId: 'doraemon',
    floorPlanId: 'plan-mall-b1',
    areaId: 'area-mall-parking-east',
    x: 8,
    y: 14,
    width: 48,
    height: 52,
    labelX: 30,
    labelY: 40,
  },
  {
    id: 'geo-mall-loading',
    projectId: 'doraemon',
    floorPlanId: 'plan-mall-b1',
    areaId: 'area-mall-loading',
    x: 60,
    y: 18,
    width: 30,
    height: 34,
    labelX: 74,
    labelY: 35,
  },
  {
    id: 'geo-fuel-canopy',
    projectId: 'doraemon',
    floorPlanId: 'plan-fuel-site',
    areaId: 'area-fuel-canopy',
    x: 8,
    y: 16,
    width: 48,
    height: 36,
    labelX: 30,
    labelY: 34,
  },
  {
    id: 'geo-fuel-island-1',
    projectId: 'doraemon',
    floorPlanId: 'plan-fuel-site',
    areaId: 'area-fuel-island-1',
    x: 24,
    y: 28,
    width: 16,
    height: 10,
    labelX: 32,
    labelY: 35,
  },
  {
    id: 'geo-fuel-building',
    projectId: 'doraemon',
    floorPlanId: 'plan-fuel-site',
    areaId: 'area-fuel-building',
    x: 60,
    y: 14,
    width: 30,
    height: 30,
    labelX: 74,
    labelY: 30,
  },
  {
    id: 'geo-fuel-unloading',
    projectId: 'doraemon',
    floorPlanId: 'plan-fuel-site',
    areaId: 'area-fuel-unloading',
    x: 60,
    y: 52,
    width: 30,
    height: 24,
    labelX: 74,
    labelY: 64,
  },
  {
    id: 'geo-fuel-store',
    projectId: 'doraemon',
    floorPlanId: 'plan-fuel-building-1f',
    areaId: 'area-fuel-store',
    x: 8,
    y: 14,
    width: 48,
    height: 42,
    labelX: 30,
    labelY: 36,
  },
  {
    id: 'geo-fuel-cashier',
    projectId: 'doraemon',
    floorPlanId: 'plan-fuel-building-1f',
    areaId: 'area-fuel-cashier',
    x: 10,
    y: 58,
    width: 26,
    height: 22,
    labelX: 22,
    labelY: 70,
  },
  {
    id: 'geo-fuel-duty',
    projectId: 'doraemon',
    floorPlanId: 'plan-fuel-building-1f',
    areaId: 'area-fuel-duty',
    x: 60,
    y: 20,
    width: 30,
    height: 36,
    labelX: 74,
    labelY: 38,
  },
  {
    id: 'geo-chem-control-room',
    projectId: 'doraemon',
    floorPlanId: 'plan-chem-control-1f',
    areaId: 'area-chem-control-room',
    x: 8,
    y: 14,
    width: 48,
    height: 42,
    labelX: 30,
    labelY: 36,
  },
  {
    id: 'geo-chem-shift-room',
    projectId: 'doraemon',
    floorPlanId: 'plan-chem-control-1f',
    areaId: 'area-chem-shift-room',
    x: 60,
    y: 16,
    width: 30,
    height: 32,
    labelX: 74,
    labelY: 32,
  },
  {
    id: 'geo-chem-kettle',
    projectId: 'doraemon',
    floorPlanId: 'plan-chem-process',
    areaId: 'area-chem-kettle',
    x: 8,
    y: 14,
    width: 48,
    height: 48,
    labelX: 30,
    labelY: 38,
  },
  {
    id: 'geo-chem-feeding',
    projectId: 'doraemon',
    floorPlanId: 'plan-chem-process',
    areaId: 'area-chem-feeding',
    x: 60,
    y: 18,
    width: 30,
    height: 34,
    labelX: 74,
    labelY: 35,
  },
  {
    id: 'geo-chem-tank',
    projectId: 'doraemon',
    floorPlanId: 'plan-chem-tank',
    areaId: 'area-chem-tank-farm',
    x: 8,
    y: 14,
    width: 48,
    height: 48,
    labelX: 30,
    labelY: 38,
  },
  {
    id: 'geo-chem-loading',
    projectId: 'doraemon',
    floorPlanId: 'plan-chem-tank',
    areaId: 'area-chem-loading',
    x: 60,
    y: 18,
    width: 30,
    height: 38,
    labelX: 74,
    labelY: 37,
  },
  {
    id: 'geo-care-lobby',
    projectId: 'doraemon',
    floorPlanId: 'plan-care-1f',
    areaId: 'area-care-lobby',
    x: 8,
    y: 14,
    width: 48,
    height: 42,
    labelX: 30,
    labelY: 36,
  },
  {
    id: 'geo-care-nurse',
    projectId: 'doraemon',
    floorPlanId: 'plan-care-1f',
    areaId: 'area-care-nurse',
    x: 60,
    y: 14,
    width: 30,
    height: 30,
    labelX: 74,
    labelY: 30,
  },
  {
    id: 'geo-care-activity',
    projectId: 'doraemon',
    floorPlanId: 'plan-care-1f',
    areaId: 'area-care-activity',
    x: 60,
    y: 48,
    width: 30,
    height: 32,
    labelX: 74,
    labelY: 65,
  },
  {
    id: 'geo-care-east-ward',
    projectId: 'doraemon',
    floorPlanId: 'plan-care-3f',
    areaId: 'area-care-east-ward',
    x: 8,
    y: 14,
    width: 82,
    height: 42,
    labelX: 48,
    labelY: 36,
  },
  {
    id: 'geo-tech-office',
    projectId: 'doraemon',
    floorPlanId: 'plan-tech-rd-2f',
    areaId: 'area-tech-open-office',
    x: 8,
    y: 14,
    width: 48,
    height: 42,
    labelX: 30,
    labelY: 36,
  },
  {
    id: 'geo-tech-lab',
    projectId: 'doraemon',
    floorPlanId: 'plan-tech-rd-2f',
    areaId: 'area-tech-lab',
    x: 60,
    y: 14,
    width: 30,
    height: 30,
    labelX: 74,
    labelY: 30,
  },
  {
    id: 'geo-tech-meeting',
    projectId: 'doraemon',
    floorPlanId: 'plan-tech-rd-2f',
    areaId: 'area-tech-meeting',
    x: 60,
    y: 48,
    width: 30,
    height: 32,
    labelX: 74,
    labelY: 65,
  },
  {
    id: 'geo-tech-server',
    projectId: 'doraemon',
    floorPlanId: 'plan-tech-dc-1f',
    areaId: 'area-tech-server-room',
    x: 8,
    y: 14,
    width: 48,
    height: 52,
    labelX: 30,
    labelY: 40,
  },
  {
    id: 'geo-tech-ups',
    projectId: 'doraemon',
    floorPlanId: 'plan-tech-dc-1f',
    areaId: 'area-tech-ups',
    x: 60,
    y: 18,
    width: 30,
    height: 34,
    labelX: 74,
    labelY: 35,
  },
]

export function createProjectAreaMockAdapter(): ProjectAreaAdapter {
  return {
    async getSettings(projectId) {
      return getProjectAreaSettings(projectId)
    },
    async resetProjectData(projectId) {
      const seedAreas = AREAS
        .map(normalizeArea)
        .map(cloneArea)
        .filter((area) => area.projectId === projectId)
      if (!seedAreas.length) return err('NOT_FOUND', '未找到项目区域配置')

      areaState = [
        ...areaState.filter((area) => area.projectId !== projectId),
        ...seedAreas,
      ].sort((a, b) => a.sortOrder - b.sortOrder)

      whiteModelExtractionRuntime.resetProject(projectId)

      return getProjectAreaSettings(projectId)
    },
    async updateArea(projectId, areaId, input) {
      const index = areaState.findIndex((area) => area.projectId === projectId && area.id === areaId)
      if (index < 0) return err('NOT_FOUND', '未找到要编辑的区域')
      if (!input.name.trim()) return err('VALIDATION_FAILED', '区域名称不能为空')
      if (!input.code.trim()) return err('VALIDATION_FAILED', '区域编码不能为空')
      if (input.planMode === 'inherit' && !areaState[index]?.parentId) {
        return err('VALIDATION_FAILED', '根空间不能使用上级图纸')
      }

      areaState = areaState.map((area, currentIndex) =>
        currentIndex === index
          ? {
              ...area,
              name: input.name.trim(),
              code: input.code.trim(),
              aliases: input.aliases.map((alias) => alias.trim()).filter(Boolean),
              description: input.description.trim(),
              sortOrder: input.sortOrder,
              planMode: input.planMode,
              floorPlanId: input.planMode === 'own' ? area.floorPlanId : undefined,
            }
          : area,
      )

      return getProjectAreaSettings(projectId)
    },
    async moveArea(projectId, areaId, input) {
      const area = areaState.find((item) => item.projectId === projectId && item.id === areaId)
      if (!area) return err('NOT_FOUND', '未找到要移动的区域')
      if (area.type === 'site') return err('VALIDATION_FAILED', '项目根空间不能移动')

      const parent = input.parentId
        ? areaState.find((item) => item.projectId === projectId && item.id === input.parentId)
        : null
      if (input.parentId && !parent) return err('NOT_FOUND', '未找到目标上级空间')
      if (input.parentId === areaId || isDescendant(areaId, input.parentId)) {
        return err('VALIDATION_FAILED', '不能移动到自身或下级区域')
      }

      areaState = areaState.map((item) =>
        item.id === areaId
          ? {
              ...item,
              parentId: input.parentId,
              sortOrder: input.sortOrder,
            }
          : item,
      )

      return getProjectAreaSettings(projectId)
    },
    async startWhiteModelJob(projectId, floorPlanId) {
      const result = whiteModelExtractionRuntime.startWhiteModelJob({ projectId, floorPlanId })
      if (!result) return err('NOT_FOUND', '未找到要制作白模的平面图')

      return getProjectAreaSettings(projectId)
    },
    async selectWhiteModelCandidate(projectId, floorPlanId, candidateId) {
      const result = whiteModelExtractionRuntime.selectWhiteModelCandidate(projectId, floorPlanId, candidateId)
      if (!result) return err('NOT_FOUND', '未找到白模结果')

      return getProjectAreaSettings(projectId)
    },
    async publishWhiteModelCandidate(projectId, floorPlanId, candidateId) {
      const result = whiteModelExtractionRuntime.publishWhiteModelCandidate(projectId, floorPlanId, candidateId)
      if (!result) return err('NOT_FOUND', '未找到白模结果')

      return getProjectAreaSettings(projectId)
    },
  }
}

function getProjectAreaSettings(projectId: string) {
  const projectAreas = areaState.filter((area) => area.projectId === projectId)
  if (!projectAreas.length) {
    return err('NOT_FOUND', '未找到项目区域配置')
  }

  const data: ProjectAreaSettings = {
    projectId,
    rootAreaId: projectAreas.find((area) => area.type === 'site')?.id ?? projectAreas[0]?.id ?? '',
    areas: projectAreas.map(cloneArea),
    floorPlans: FLOOR_PLANS.filter((plan) => plan.projectId === projectId).map(cloneFloorPlan),
    geometries: GEOMETRIES.filter((geometry) => geometry.projectId === projectId),
    whiteModelJobs: whiteModelExtractionRuntime.listJobs(projectId),
    whiteModelCandidates: whiteModelExtractionRuntime.listCandidates(projectId),
  }

  return ok(data)
}

function normalizeArea(area: ProjectAreaSeed): ProjectArea {
  return {
    ...area,
    planMode: area.planMode ?? 'inherit',
  }
}

function cloneArea(area: ProjectArea): ProjectArea {
  return {
    ...area,
    aliases: [...area.aliases],
  }
}

function cloneFloorPlan(plan: ProjectFloorPlan): ProjectFloorPlan {
  return {
    ...plan,
    sourceReference: plan.sourceReference ? { ...plan.sourceReference } : undefined,
  }
}

function isDescendant(ancestorId: string, areaId: string | undefined) {
  let parentId = areaId
  while (parentId) {
    if (parentId === ancestorId) return true
    parentId = areaState.find((area) => area.id === parentId)?.parentId
  }
  return false
}

