import type { DeviceTemplate } from '@device-manager-ui/services/device-library/types'

export const DEVICE_LIBRARY: DeviceTemplate[] = [
  {
    id: 'temperature-humidity-sensor',
    name: '温湿度传感器',
    summary: '单个环境采集终端，用于中庭、值班室、活动室、机房通道、实验室和住区房间的温湿度监测。',
    category: 'sensor',
    scenarios: ['environment', 'data-center', 'care-assist'],
    industries: ['commercial', 'care', 'building', 'data-center', 'park', 'chemical'],
    supportedBrands: ['海为 HaiWell', '通用 MQTT 传感器', '通用 Zigbee 传感器'],
    supportedModels: [
      {
        brand: '海为 HaiWell',
        models: ['H01ZB 温湿度传感器', 'A8-WiFi 环境采集器', 'C16S2R 温湿度采集终端'],
        note: '适合公共空间、机房通道和实验室环境点位。',
        accessMode: 'direct',
        accessName: 'HaiWell MQTT 直连',
        connectionHint: '设备写入平台 MQTT 地址和认证信息后，等待心跳即可测试。',
        requirements: ['准备 secureId / secureKey', '配置 MQTT 地址', '确认设备出站网络'],
      },
      {
        brand: '通用 MQTT 传感器',
        models: ['MQTT 温湿度传感器', 'Wi-Fi 温湿度终端', 'NB-IoT 温湿度终端'],
        note: '适合多品牌温湿度终端统一映射。',
        accessMode: 'direct',
        accessName: '通用 MQTT Topic 映射',
        connectionHint: '映射 temperature、humidity、battery 和 signal 字段。',
        requirements: ['确认 Topic 格式', '准备字段样例', '配置设备认证'],
      },
      {
        brand: '通用 Zigbee 传感器',
        models: ['Zigbee 温湿度传感器', 'LoRa 温湿度终端', 'BLE 环境标签'],
        note: '适合低功耗房间级环境监测。',
        accessMode: 'edge',
        accessName: '低功耗网关映射',
        connectionHint: '先在边缘网关完成子设备入网，再同步温湿度和电池。',
        requirements: ['子设备已入网', '准备网关子设备编号', '确认电池上报周期'],
      },
    ],
    modelKeywords: ['温度', '湿度', '环境', '房间', '实验室', '机房通道'],
    deviceType: '直连设备',
    sourceProduct: '温湿度传感器产品模板',
    accessModes: ['direct', 'edge'],
    accessName: '温湿度传感器接入',
    connectionHint: '填写设备编号和字段映射后，可查看温湿度、电池和信号状态。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'telemetry', key: 'temperature', name: '温度', desc: '实时温度、最高值、最低值和趋势。', isKeyMetric: true },
      { kind: 'telemetry', key: 'humidity', name: '湿度', desc: '实时湿度和区间统计。', isKeyMetric: true },
      { kind: 'telemetry', key: 'battery', name: '电池电压', desc: '低功耗设备电池监测。', isKeyMetric: true },
      { kind: 'telemetry', key: 'signal', name: '信号强度', desc: '低功耗网络信号质量。' },
      { kind: 'status', key: 'deviceStatus', name: '设备状态', desc: '在线、离线、低电量和弱信号。' },
    ],
    requirements: ['设备已写入平台地址或已入网', '已准备设备认证信息', '现场网络或网关已可用'],
    testSteps: ['校验认证信息', '等待设备心跳', '读取温湿度', '触发一条阈值样例'],
    projectDefaults: ['创建设备档案', '启用离线 / 低电量 / 越限告警', '生成温湿度历史趋势'],
    faultCodeDict: [
      {
        code: 'TH01',
        protocolField: 'status_code',
        name: '设备离线',
        severity: 'critical',
        cause: '设备超过 3 个心跳周期未上报，常见原因是电池耗尽、信号弱或网关离线。',
        recommendedAction: '检查电池电压和信号强度；若同网关多台离线，优先排查网关。',
        knowledgeRefs: ['kb-th-sensor'],
      },
      {
        code: 'TH11',
        protocolField: 'alarm_flag',
        name: '温度越限',
        severity: 'warning',
        cause: '温度连续超过设备模板预设范围，常见于通风不足、门长开或局部热源影响。',
        recommendedAction: '现场核查通风、门禁和局部热源；必要时调整设备安装位置。',
        knowledgeRefs: ['kb-th-range'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'temperature', name: '温度', min: -10, max: 40, typicalAvg: 22, unit: '°C', hint: '公共空间建议 18-28°C；机房通道建议 18-27°C。' },
      { pointKey: 'humidity', name: '湿度', min: 30, max: 75, typicalAvg: 55, unit: '%', hint: '普通空间建议 40-70%；低于 30% 需注意静电。' },
      { pointKey: 'battery', name: '电池电压', min: 2.8, max: 3.6, typicalAvg: 3.2, unit: 'V', hint: '低于 2.8V 建议更换。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-th-sensor',
        title: '温湿度传感器离线诊断',
        body: '优先检查电池、信号和最近心跳。同网关多台设备离线时，先排查网关和弱电间网络。',
        tags: ['温湿度', '离线', '电池'],
      },
      {
        id: 'kb-th-range',
        title: '温湿度阈值参考',
        body: '普通办公和公共空间建议 18-28°C、湿度 40-70%；机房通道建议 18-27°C、湿度 40-60%。',
        tags: ['阈值', '环境'],
      },
    ],
  },
  {
    id: 'water-leak-sensor',
    name: '水浸传感器',
    summary: '单个水浸探测终端，用于车库排水沟、弱电间地面、机柜通道地板下和康养卫生间。',
    category: 'sensor',
    scenarios: ['environment', 'data-center', 'fire-safety'],
    industries: ['commercial', 'care', 'data-center', 'building', 'park'],
    supportedBrands: ['海为 HaiWell', '通用 MQTT 传感器', '通用 Zigbee 传感器'],
    supportedModels: [
      {
        brand: '海为 HaiWell',
        models: ['WL01 水浸传感器', 'LoRa 水浸终端', 'NB-IoT 水浸探测器'],
        note: '适合车库、弱电间、机柜通道和卫生间点位。',
        accessMode: 'direct',
        accessName: 'MQTT / NB-IoT 直连',
        connectionHint: '映射 water、battery、signal 和 deviceStatus。',
        requirements: ['准备设备编号', '确认探头位置', '确认上报周期'],
      },
      {
        brand: '通用 MQTT 传感器',
        models: ['MQTT 水浸', '4G 水浸终端', 'NB-IoT 水浸'],
        note: '适合独立联网水浸设备。',
        accessMode: 'direct',
        accessName: '通用 MQTT Topic 映射',
        connectionHint: '将水浸状态和电池字段映射为统一物模型。',
        requirements: ['确认 Topic 格式', '准备字段样例', '配置设备认证'],
      },
      {
        brand: '通用 Zigbee 传感器',
        models: ['Zigbee 水浸', 'LoRa 水浸', '蓝牙水浸标签'],
        note: '适合通过网关接入的低功耗水浸点位。',
        accessMode: 'edge',
        accessName: '低功耗网关映射',
        connectionHint: '先入网再同步水浸状态、电池和信号。',
        requirements: ['子设备已入网', '确认安装位置', '确认电池周期'],
      },
    ],
    modelKeywords: ['水浸', '防汛', '排水沟', '弱电间', '机柜通道', '卫生间'],
    deviceType: '直连设备',
    sourceProduct: '水浸传感器产品模板',
    accessModes: ['direct', 'edge'],
    accessName: '水浸传感器接入',
    connectionHint: '按点位映射水浸状态、电池和信号强度。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'status', key: 'water', name: '水浸状态', desc: '正常、有水、探头故障。', isKeyMetric: true },
      { kind: 'telemetry', key: 'battery', name: '电池电压', desc: '低功耗水浸终端电池状态。', isKeyMetric: true },
      { kind: 'telemetry', key: 'signal', name: '信号强度', desc: '低功耗网络信号质量。' },
      { kind: 'alarm', key: 'alarm', name: '水浸告警', desc: '水浸、低电量、离线和探头故障。' },
    ],
    requirements: ['确认探头安装位置', '设备已入网或已写入平台地址', '准备水浸测试样例'],
    testSteps: ['读取心跳', '触发探头水浸测试', '校验恢复事件', '读取电池字段'],
    projectDefaults: ['创建设备档案', '启用水浸 / 低电量 / 离线告警', '生成防汛点位卡'],
    faultCodeDict: [
      {
        code: 'WL01',
        protocolField: 'water_status',
        name: '水浸触发',
        severity: 'critical',
        cause: '探头检测到有水，可能是排水沟积水、管路渗漏或卫生间溢水。',
        recommendedAction: '通知现场确认水源；涉弱电区域优先保护附近设备供电。',
        knowledgeRefs: ['kb-water-leak'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'battery', name: '电池电压', min: 2.8, max: 3.6, typicalAvg: 3.2, unit: 'V', hint: '低于 2.8V 建议更换。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-water-leak',
        title: '水浸点位排查',
        body: '先确认是否真实积水，再排查探头位置和防水盒。弱电间水浸需同步查看地板下管路和排水管路。',
        tags: ['水浸', '防汛'],
      },
    ],
  },
  {
    id: 'smoke-detector',
    name: '无线烟感',
    summary: '单个烟雾探测终端，用于服务台、消防通道、活动室、走廊和住区等消防监测点位。',
    category: 'sensor',
    scenarios: ['fire-safety', 'environment'],
    industries: ['commercial', 'care', 'building', 'park', 'security'],
    supportedBrands: ['海为 HaiWell', '通用 MQTT 传感器', '通用 Zigbee 传感器'],
    supportedModels: [
      {
        brand: '海为 HaiWell',
        models: ['NB-IoT 烟感', 'LoRa 烟感', 'Zigbee 烟雾探测器'],
        note: '适合商业和康养空间的低功耗烟感点位。',
        accessMode: 'direct',
        accessName: 'MQTT / NB-IoT 直连',
        connectionHint: '映射 smoke、battery、tamper 和 deviceStatus 字段。',
        requirements: ['准备设备编号', '确认上报周期', '完成安装位置登记'],
      },
      {
        brand: '通用 MQTT 传感器',
        models: ['MQTT 烟感', 'NB-IoT 烟感', '4G 独立烟感'],
        note: '适合多品牌烟感统一接入。',
        accessMode: 'direct',
        accessName: '通用 MQTT Topic 映射',
        connectionHint: '将 smoke、alarmFlag、battery 映射为统一物模型。',
        requirements: ['确认 Topic 格式', '准备告警样例', '配置设备认证'],
      },
      {
        brand: '通用 Zigbee 传感器',
        models: ['Zigbee 烟感', 'LoRa 烟感', '低功耗烟雾终端'],
        note: '适合通过网关统一接入的楼层烟感。',
        accessMode: 'edge',
        accessName: '低功耗网关映射',
        connectionHint: '先入网再同步烟雾状态、电池和拆卸告警。',
        requirements: ['子设备已入网', '确认楼层位置', '确认电池周期'],
      },
    ],
    modelKeywords: ['烟感', '烟雾', '消防', '低电量', '拆卸'],
    deviceType: '直连设备',
    sourceProduct: '烟雾探测器产品模板',
    accessModes: ['direct', 'edge'],
    accessName: '无线烟感接入',
    connectionHint: '按设备编号和字段样例完成烟雾状态、电池、拆卸告警映射。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'status', key: 'smoke', name: '烟雾状态', desc: '正常、预警、告警。', isKeyMetric: true },
      { kind: 'telemetry', key: 'battery', name: '电池电压', desc: '烟感电池电压或电量。', isKeyMetric: true },
      { kind: 'status', key: 'tamper', name: '拆卸状态', desc: '设备拆卸、外壳打开或安装异常。' },
      { kind: 'alarm', key: 'alarm', name: '消防告警', desc: '烟雾告警、低电量和设备离线。' },
    ],
    requirements: ['完成安装点位登记', '设备已写入平台地址或网关已入网', '准备告警测试样例'],
    testSteps: ['读取设备心跳', '读取烟雾状态', '触发测试告警', '校验低电量字段'],
    projectDefaults: ['创建设备档案', '启用烟雾 / 低电量 / 离线告警', '生成消防监测卡'],
    faultCodeDict: [
      {
        code: 'SD01',
        protocolField: 'smoke_status',
        name: '烟雾告警',
        severity: 'critical',
        cause: '探测到烟雾或测试烟雾事件，可能来自真实火情、施工烟尘或测试操作。',
        recommendedAction: '先按消防流程现场确认；若确认为施工影响，配置施工时段策略。',
        knowledgeRefs: ['kb-smoke-detector'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'battery', name: '电池电压', min: 2.8, max: 3.6, typicalAvg: 3.2, unit: 'V', hint: '低于 2.8V 建议更换电池。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-smoke-detector',
        title: '烟感告警处置',
        body: '烟感告警先现场确认，不应先远程复位。施工、装修和厨房烟尘需要记录原因并设置临时策略。',
        tags: ['烟感', '消防'],
      },
    ],
  },
  {
    id: 'gas-lel-detector',
    name: '可燃气体探测器',
    summary: '单个 LEL 可燃气体探测终端，用于加油岛、卸油区、储罐围堰和化工装置区。',
    category: 'sensor',
    scenarios: ['fuel-safety', 'chemical-safety', 'environment'],
    industries: ['energy', 'chemical', 'manufacturing', 'park', 'security'],
    supportedBrands: ['汉威科技', '霍尼韦尔', '通用气体探测器'],
    supportedModels: [
      {
        brand: '汉威科技',
        models: ['GTQ-BS03', 'BS03-II', 'KB5000'],
        note: '适合加油作业区、卸油区和储罐围堰固定式探测。',
        accessMode: 'direct',
        accessName: '4G / MQTT 直连',
        connectionHint: '配置平台 MQTT 地址后，将 gas、alarmFlag、faultFlag 映射为统一字段。',
        requirements: ['确认探测气体类型', '完成现场标定', '准备上报字段样例'],
      },
      {
        brand: '霍尼韦尔',
        models: ['Sensepoint XCD', 'Searchpoint Optima Plus'],
        note: '适合危化厂区高可靠安全监测点位。',
        accessMode: 'collector',
        accessName: 'RS485 / Modbus 采集',
        connectionHint: '通过安全采集器读取浓度、报警状态和故障状态寄存器。',
        requirements: ['已部署安全采集器', '准备寄存器表', '确认标定周期'],
      },
      {
        brand: '通用气体探测器',
        models: ['可燃气体探测器', '防爆可燃气体探测器', '点型气体探测器'],
        note: '适合多厂家混用现场。',
        accessMode: 'collector',
        accessName: '通用 Modbus 采集',
        connectionHint: '按量程映射 gas、alarmFlag 和 faultFlag。',
        requirements: ['准备气体类型', '确认量程', '确认报警继电器映射'],
      },
    ],
    modelKeywords: ['可燃气体', 'LEL', '加油站', '卸油区', '储罐区', '防爆'],
    deviceType: '直连设备',
    sourceProduct: '可燃气体探测器产品模板',
    accessModes: ['direct', 'collector'],
    accessName: '可燃气体探测器接入',
    connectionHint: '按设备量程映射浓度、报警状态、故障状态和标定状态。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'telemetry', key: 'gas', name: '可燃气体', desc: '以 %LEL 上报的可燃气体浓度。', isKeyMetric: true },
      { kind: 'status', key: 'alarmFlag', name: '报警状态', desc: '预警、报警、故障和标定状态。', isKeyMetric: true },
      { kind: 'status', key: 'calibration', name: '标定状态', desc: '正常、标定中、标定过期。' },
    ],
    requirements: ['确认气体类型和量程', '完成现场标定', '确认防爆和安装位置要求'],
    testSteps: ['读取当前浓度', '触发一次测试报警', '校验声光联动状态', '确认故障位可上报'],
    projectDefaults: ['创建设备档案', '启用预警 / 报警规则', '生成浓度趋势'],
    faultCodeDict: [
      {
        code: 'G01',
        protocolField: 'alarm_flag',
        name: '可燃气体超限',
        severity: 'critical',
        cause: '气体浓度超过预警或报警线，可能来自泄漏、卸油作业波动、通风不足或传感器漂移。',
        recommendedAction: '先执行现场安全确认和通风；油气场景暂停临近作业；确认无泄漏后再复位告警。',
        knowledgeRefs: ['kb-gas-detector'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'gas', name: '可燃气体', min: 0, max: 10, typicalAvg: 0, unit: '%LEL', hint: '10%LEL 进入预警，20%LEL 通常进入报警。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-gas-detector',
        title: '可燃气体超限处置',
        body: '先保护人身安全，再判断作业状态。卸油区需同步确认静电接地和通风状态。',
        tags: ['可燃气体', '油气', '防爆'],
      },
    ],
  },
  {
    id: 'voc-toxic-gas-detector',
    name: 'VOC / 有毒气体探测器',
    summary: '单个 VOC、H2S 或氧含量探测终端，用于投料间、实验室、储罐区和密闭空间作业点。',
    category: 'sensor',
    scenarios: ['chemical-safety', 'environment', 'industrial-collect'],
    industries: ['chemical', 'manufacturing', 'energy', 'park', 'security'],
    supportedBrands: ['汉威科技', '霍尼韦尔', '通用气体探测器'],
    supportedModels: [
      {
        brand: '汉威科技',
        models: ['ES10B', 'KB5000 PID', '固定式 VOC 探测器'],
        note: '适合投料间、实验室和储罐区 VOC 监测。',
        accessMode: 'direct',
        accessName: '4G / MQTT 直连',
        connectionHint: '将 voc、h2s、oxygen、alarmFlag 映射为统一字段。',
        requirements: ['确认探测气体类型', '完成现场标定', '准备字段样例'],
      },
      {
        brand: '霍尼韦尔',
        models: ['RAEGuard 2 PID', 'Sensepoint XCD RFD', 'Searchline Excel Plus'],
        note: '适合危化厂区高可靠 VOC / 有毒气体监测。',
        accessMode: 'collector',
        accessName: 'RS485 / Modbus 采集',
        connectionHint: '通过安全采集器读取浓度、报警状态和故障状态寄存器。',
        requirements: ['已部署安全采集器', '准备寄存器表', '确认标定周期'],
      },
      {
        brand: '通用气体探测器',
        models: ['VOC 探测器', '硫化氢探测器', '氧含量探测器'],
        note: '适合多厂家混用的单点气体探测。',
        accessMode: 'collector',
        accessName: '通用 Modbus 采集',
        connectionHint: '按气体类型选择点位字段和正常范围。',
        requirements: ['准备气体类型', '确认量程', '确认报警状态字'],
      },
    ],
    modelKeywords: ['VOC', 'H2S', '氧含量', '投料间', '实验室', '密闭空间'],
    deviceType: '直连设备',
    sourceProduct: 'VOC / 有毒气体探测器产品模板',
    accessModes: ['direct', 'collector'],
    accessName: 'VOC / 有毒气体探测器接入',
    connectionHint: '按气体类型映射浓度、量程、报警状态和故障状态。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'telemetry', key: 'voc', name: 'VOC', desc: '挥发性有机物浓度。', isKeyMetric: true },
      { kind: 'telemetry', key: 'h2s', name: '硫化氢', desc: '有毒气体浓度。', isKeyMetric: true },
      { kind: 'telemetry', key: 'oxygen', name: '氧含量', desc: '密闭空间作业参考。', isKeyMetric: true },
      { kind: 'status', key: 'alarmFlag', name: '报警状态', desc: '预警、报警、故障和标定状态。', isKeyMetric: true },
    ],
    requirements: ['确认气体类型和量程', '完成现场标定', '确认防爆和安装位置要求'],
    testSteps: ['读取当前浓度', '触发测试报警', '确认故障位可上报', '校验标定状态'],
    projectDefaults: ['创建设备档案', '启用预警 / 报警规则', '生成浓度趋势'],
    faultCodeDict: [
      {
        code: 'T01',
        protocolField: 'alarm_flag',
        name: '气体浓度超限',
        severity: 'critical',
        cause: 'VOC、H2S 或氧含量超过安全范围，可能来自泄漏、投料波动、通风不足或探头漂移。',
        recommendedAction: '按现场安全流程确认人员安全和通风状态；确认无泄漏后再复位。',
        knowledgeRefs: ['kb-toxic-gas'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'voc', name: 'VOC', min: 0, max: 20, typicalAvg: 3, unit: 'ppm', hint: '投料时段可短时升高，需结合持续时间。' },
      { pointKey: 'oxygen', name: '氧含量', min: 19.5, max: 23.5, typicalAvg: 20.9, unit: '%VOL', hint: '低于 19.5% 需要安全复核。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-toxic-gas',
        title: 'VOC / 有毒气体探测器维护',
        body: '固定式气体探测器需要按厂家周期标定。标定过期、探头污染或采集回路断线都会造成误报或无数据。',
        tags: ['VOC', '标定', '危化'],
      },
    ],
  },
  {
    id: 'carbon-monoxide-sensor',
    name: '一氧化碳探测器',
    summary: '单个 CO 浓度采集终端，用于地下车库、锅炉间、通风不良通道和密闭空间的安全监测。',
    category: 'sensor',
    scenarios: ['environment', 'fire-safety', 'commercial-ops'],
    industries: ['commercial', 'building', 'park', 'care', 'security'],
    supportedBrands: ['汉威科技', '霍尼韦尔', '通用气体探测器'],
    supportedModels: [
      {
        brand: '汉威科技',
        models: ['固定式 CO 探测器', 'NB-IoT CO 探测器', 'LoRa CO 探测终端'],
        note: '适合地下车库、设备间和封闭通道的 CO 点位。',
        accessMode: 'direct',
        accessName: '4G / MQTT 直连',
        connectionHint: '将 co、alarmFlag、faultFlag 和 deviceStatus 映射为统一字段。',
        requirements: ['确认量程', '完成安装位置登记', '准备告警测试样例'],
      },
      {
        brand: '霍尼韦尔',
        models: ['Sensepoint XCD CO', 'XNX Universal Transmitter CO'],
        note: '适合高可靠固定式 CO 监测点位。',
        accessMode: 'collector',
        accessName: 'RS485 / Modbus 采集',
        connectionHint: '通过采集器读取 CO 浓度、报警状态和故障状态。',
        requirements: ['准备寄存器表', '确认设备地址', '确认标定周期'],
      },
      {
        brand: '通用气体探测器',
        models: ['CO 探测器', '车库 CO 终端', '一氧化碳变送器'],
        note: '适合多厂家 CO 终端统一接入。',
        accessMode: 'collector',
        accessName: '通用 Modbus 采集',
        connectionHint: '按 ppm 量程映射浓度、报警状态和故障位。',
        requirements: ['确认量程', '准备寄存器表', '确认地址拨码'],
      },
    ],
    modelKeywords: ['CO', '一氧化碳', '地下车库', '通风', '密闭空间'],
    deviceType: '直连设备',
    sourceProduct: '一氧化碳探测器产品模板',
    accessModes: ['direct', 'collector'],
    accessName: '一氧化碳探测器接入',
    connectionHint: '按设备量程映射 CO 浓度、报警位、故障位和标定状态。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'telemetry', key: 'co', name: 'CO 浓度', desc: '以 ppm 上报的一氧化碳浓度。', isKeyMetric: true },
      { kind: 'status', key: 'alarmFlag', name: '报警状态', desc: '正常、预警、报警和故障。', isKeyMetric: true },
      { kind: 'status', key: 'calibration', name: '标定状态', desc: '正常、标定中、标定过期。' },
    ],
    requirements: ['确认量程和安装高度', '设备已写入平台地址或采集器已连通', '准备告警测试样例'],
    testSteps: ['读取当前浓度', '触发测试报警', '校验恢复事件', '读取故障位'],
    projectDefaults: ['创建设备档案', '启用 CO 预警 / 报警规则', '生成浓度趋势'],
    faultCodeDict: [
      {
        code: 'CO01',
        protocolField: 'alarm_flag',
        name: 'CO 浓度超限',
        severity: 'critical',
        cause: 'CO 浓度超过安全阈值，常见于车辆怠速聚集、通风不足或探头漂移。',
        recommendedAction: '先确认人员安全并加强通风；恢复后核对标定状态和设备安装位置。',
        knowledgeRefs: ['kb-co-sensor'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'co', name: 'CO 浓度', min: 0, max: 24, typicalAvg: 5, unit: 'ppm', hint: '车库场景通常以 24ppm 作为预警参考，需结合本地规范配置。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-co-sensor',
        title: 'CO 探测器运维参考',
        body: 'CO 探测器应按厂家周期标定。长期零漂、通风短时变化和安装高度偏差都会影响趋势判断。',
        tags: ['CO', '车库', '标定'],
      },
    ],
  },
  {
    id: 'co2-air-quality-sensor',
    name: 'CO2 / 空气质量传感器',
    summary: '单个室内空气质量采集终端，用于会议室、活动室、康养房间、商业中庭和办公区。',
    category: 'sensor',
    scenarios: ['environment', 'care-assist', 'commercial-ops'],
    industries: ['commercial', 'care', 'building', 'park'],
    supportedBrands: ['海为 HaiWell', '通用 MQTT 传感器', '通用 Zigbee 传感器'],
    supportedModels: [
      {
        brand: '海为 HaiWell',
        models: ['CO2 空气质量终端', 'A8-WiFi 空气质量采集器', 'LoRa 空气质量传感器'],
        note: '适合室内舒适度和人员密集空间监测。',
        accessMode: 'direct',
        accessName: 'MQTT / Wi-Fi 直连',
        connectionHint: '映射 co2、pm25、tvoc、temperature 和 humidity 字段。',
        requirements: ['确认采集字段', '配置 MQTT 地址', '完成点位登记'],
      },
      {
        brand: '通用 MQTT 传感器',
        models: ['MQTT CO2 传感器', 'Wi-Fi 空气质量终端', 'NB-IoT 空气质量终端'],
        note: '适合多品牌空气质量终端统一接入。',
        accessMode: 'direct',
        accessName: '通用 MQTT Topic 映射',
        connectionHint: '按字段样例映射 CO2、PM2.5、TVOC 和温湿度。',
        requirements: ['确认 Topic 格式', '准备字段样例', '配置设备认证'],
      },
      {
        brand: '通用 Zigbee 传感器',
        models: ['Zigbee CO2 传感器', 'BLE 空气质量标签', 'LoRa 空气质量终端'],
        note: '适合房间级低功耗空气质量采集。',
        accessMode: 'edge',
        accessName: '低功耗网关映射',
        connectionHint: '先在网关完成子设备入网，再同步空气质量字段。',
        requirements: ['子设备已入网', '确认电池周期', '准备字段样例'],
      },
    ],
    modelKeywords: ['CO2', '空气质量', 'PM2.5', 'TVOC', '会议室', '活动室'],
    deviceType: '直连设备',
    sourceProduct: '空气质量传感器产品模板',
    accessModes: ['direct', 'edge'],
    accessName: 'CO2 / 空气质量传感器接入',
    connectionHint: '按设备字段映射 CO2、PM2.5、TVOC、温湿度、电池和信号。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'telemetry', key: 'co2', name: 'CO2', desc: '室内二氧化碳浓度。', isKeyMetric: true },
      { kind: 'telemetry', key: 'pm25', name: 'PM2.5', desc: '细颗粒物浓度。', isKeyMetric: true },
      { kind: 'telemetry', key: 'tvoc', name: 'TVOC', desc: '挥发性有机物总量。' },
      { kind: 'telemetry', key: 'battery', name: '电池电压', desc: '低功耗终端电池状态。' },
    ],
    requirements: ['确认采集字段和量程', '设备已联网或已入网', '完成房间点位登记'],
    testSteps: ['读取当前空气质量', '校验 CO2 字段', '校验温湿度字段', '触发越限样例'],
    projectDefaults: ['创建设备档案', '启用空气质量越限告警', '生成舒适度趋势'],
    faultCodeDict: [
      {
        code: 'AQ01',
        protocolField: 'alarm_flag',
        name: '空气质量越限',
        severity: 'warning',
        cause: 'CO2、PM2.5 或 TVOC 超过模板范围，常见于人员密集、通风不足或装修材料释放。',
        recommendedAction: '确认房间使用状态和通风条件；持续超限时核查传感器位置和校准状态。',
        knowledgeRefs: ['kb-air-quality'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'co2', name: 'CO2', min: 400, max: 1000, typicalAvg: 650, unit: 'ppm', hint: '室内场景建议低于 1000ppm。' },
      { pointKey: 'pm25', name: 'PM2.5', min: 0, max: 35, typicalAvg: 15, unit: 'μg/m³', hint: '持续高于 35μg/m³ 需要关注通风和过滤。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-air-quality',
        title: '空气质量传感器布点',
        body: '空气质量终端应避开门窗直吹、出风口和强热源，布点高度尽量贴近人员活动高度。',
        tags: ['空气质量', 'CO2', '布点'],
      },
    ],
  },
  {
    id: 'smart-energy-meter',
    name: '三相智能电表',
    summary: '单个电能计量终端，用于配电回路、楼层分项、商铺分户、充电区和设备用电监测。',
    category: 'meter',
    scenarios: ['energy-metering', 'industrial-collect', 'data-center'],
    industries: ['commercial', 'building', 'park', 'manufacturing', 'data-center', 'energy'],
    supportedBrands: ['安科瑞', '施耐德', '通用 Modbus 仪表'],
    supportedModels: [
      {
        brand: '安科瑞',
        models: ['ADL400', 'DTSD1352', 'AEM96'],
        note: '适合楼层分项、商铺分户和配电回路计量。',
        accessMode: 'collector',
        accessName: 'RS485 / Modbus 采集',
        connectionHint: '通过采集器读取电压、电流、功率、电能和功率因数。',
        requirements: ['准备寄存器表', '确认表地址和波特率', '确认倍率'],
      },
      {
        brand: '施耐德',
        models: ['PowerLogic PM2120', 'PM5350', 'iEM3255'],
        note: '适合高可靠回路计量和能耗看板。',
        accessMode: 'collector',
        accessName: 'Modbus RTU / TCP 采集',
        connectionHint: '按回路映射实时电参和累计电能。',
        requirements: ['确认通讯方式', '准备寄存器表', '确认互感器倍率'],
      },
      {
        brand: '通用 Modbus 仪表',
        models: ['三相电能表', '导轨式电表', '多功能电力仪表'],
        note: '适合多厂家计量终端统一接入。',
        accessMode: 'collector',
        accessName: '通用电表寄存器映射',
        connectionHint: '按寄存器表映射电压、电流、功率和电能。',
        requirements: ['准备寄存器表', '确认地址拨码', '确认倍率和单位'],
      },
    ],
    modelKeywords: ['电表', '电能', '电压', '电流', '功率', '分项计量'],
    deviceType: '子设备',
    sourceProduct: '三相智能电表产品模板',
    accessModes: ['collector'],
    accessName: '三相智能电表接入',
    connectionHint: '通过采集器接入，映射电参、电能、需量和通讯状态。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'telemetry', key: 'voltage', name: '电压', desc: '三相相电压或线电压。', isKeyMetric: true },
      { kind: 'telemetry', key: 'current', name: '电流', desc: '三相电流。', isKeyMetric: true },
      { kind: 'telemetry', key: 'activePower', name: '有功功率', desc: '当前有功功率。', isKeyMetric: true },
      { kind: 'telemetry', key: 'powerFactor', name: '功率因数', desc: '当前回路功率因数。' },
      { kind: 'telemetry', key: 'energy', name: '累计电能', desc: '正向有功电能累计值。', isKeyMetric: true },
      { kind: 'status', key: 'commStatus', name: '通讯状态', desc: '正常、超时、CRC 异常。' },
    ],
    requirements: ['确认互感器倍率', '采集器已连通', '准备寄存器表和点位倍率'],
    testSteps: ['读取电压电流', '核对倍率', '读取累计电能', '模拟通讯中断'],
    projectDefaults: ['创建设备档案', '生成能耗曲线', '启用通讯异常和越限告警'],
    faultCodeDict: [
      {
        code: 'EM01',
        protocolField: 'comm_status',
        name: '电表通讯异常',
        severity: 'warning',
        cause: '采集器读取超时、地址冲突、波特率错误或 RS485 线路异常。',
        recommendedAction: '核对地址、波特率、接线和终端电阻；同链路多表异常时先排查采集器。',
        knowledgeRefs: ['kb-energy-meter'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'voltage', name: '电压', min: 198, max: 242, typicalAvg: 220, unit: 'V', hint: '单相 220V 回路参考范围，三相需按接线方式确认。' },
      { pointKey: 'powerFactor', name: '功率因数', min: 0.8, max: 1, typicalAvg: 0.92, unit: '', hint: '低功率因数需结合业务负载判断。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-energy-meter',
        title: '电表采集常见问题',
        body: '电表接入需重点确认地址、波特率、校验位、寄存器偏移和倍率。倍率错误会造成能耗展示成倍偏差。',
        tags: ['电表', 'Modbus', '倍率'],
      },
    ],
  },
  {
    id: 'water-flow-meter',
    name: '水表 / 流量计',
    summary: '单个水量计量终端，用于生活给水、冷却水、消防水、污水排放和园区分区计量。',
    category: 'meter',
    scenarios: ['energy-metering', 'environment', 'industrial-collect'],
    industries: ['water', 'building', 'commercial', 'park', 'manufacturing'],
    supportedBrands: ['通用 Modbus 仪表', '海为 HaiWell', '安科瑞'],
    supportedModels: [
      {
        brand: '通用 Modbus 仪表',
        models: ['电磁流量计', '超声波水表', '远传水表'],
        note: '适合多厂家水量计量终端。',
        accessMode: 'collector',
        accessName: 'RS485 / Modbus 采集',
        connectionHint: '映射瞬时流量、累计流量、正反向流量和通讯状态。',
        requirements: ['准备寄存器表', '确认管径和量程', '确认单位倍率'],
      },
      {
        brand: '海为 HaiWell',
        models: ['4G 远传水表', 'LoRa 水表', 'NB-IoT 水表'],
        note: '适合分散水表的直连采集。',
        accessMode: 'direct',
        accessName: 'MQTT / NB-IoT 直连',
        connectionHint: '映射 flow、totalFlow、battery 和 signal 字段。',
        requirements: ['准备设备认证', '确认上报周期', '确认表号'],
      },
      {
        brand: '安科瑞',
        models: ['ADF400L 多用户水表采集', '远传水表采集终端'],
        note: '适合楼宇和园区分户水量采集。',
        accessMode: 'collector',
        accessName: '采集器映射',
        connectionHint: '按表号映射累计水量和通讯状态。',
        requirements: ['确认表号', '准备采集器点表', '确认单位'],
      },
    ],
    modelKeywords: ['水表', '流量计', '累计流量', '瞬时流量', '远传'],
    deviceType: '直连设备',
    sourceProduct: '水表 / 流量计产品模板',
    accessModes: ['direct', 'collector'],
    accessName: '水表 / 流量计接入',
    connectionHint: '按计量终端类型映射瞬时流量、累计流量、电池和通讯状态。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'telemetry', key: 'flow', name: '瞬时流量', desc: '当前流量值。', isKeyMetric: true },
      { kind: 'telemetry', key: 'totalFlow', name: '累计流量', desc: '累计水量或流量。', isKeyMetric: true },
      { kind: 'telemetry', key: 'battery', name: '电池电压', desc: '远传水表电池状态。' },
      { kind: 'status', key: 'commStatus', name: '通讯状态', desc: '正常、超时、弱信号。' },
    ],
    requirements: ['确认管径、量程和单位', '设备已联网或采集器已连通', '准备字段样例'],
    testSteps: ['读取瞬时流量', '核对累计值', '校验单位倍率', '模拟通讯异常'],
    projectDefaults: ['创建设备档案', '生成用水趋势', '启用用水异常和通讯异常告警'],
    faultCodeDict: [
      {
        code: 'WF01',
        protocolField: 'comm_status',
        name: '水表通讯异常',
        severity: 'warning',
        cause: '远传水表弱信号、采集链路超时、表地址错误或电池低电量。',
        recommendedAction: '检查信号、电池和表地址；同链路多表异常时先排查采集器。',
        knowledgeRefs: ['kb-water-meter'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'flow', name: '瞬时流量', min: 0, max: 120, typicalAvg: 18, unit: 'm³/h', hint: '具体范围需按管径和业务时段调整。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-water-meter',
        title: '水表 / 流量计接入校验',
        body: '水量设备接入后应核对单位和倍率。累计值倒退、长时间不变或夜间持续高流量都需要结合现场排查。',
        tags: ['水表', '流量', '倍率'],
      },
    ],
  },
  {
    id: 'level-sensor',
    name: '液位传感器',
    summary: '单个液位采集终端，用于集水井、消防水箱、污水池、储罐和雨水调蓄空间。',
    category: 'sensor',
    scenarios: ['environment', 'industrial-collect', 'chemical-safety'],
    industries: ['water', 'building', 'park', 'chemical', 'manufacturing'],
    supportedBrands: ['通用 Modbus 仪表', '海为 HaiWell', '铭控'],
    supportedModels: [
      {
        brand: '通用 Modbus 仪表',
        models: ['雷达液位计', '投入式液位计', '超声波液位计'],
        note: '适合水池、井室和储罐液位采集。',
        accessMode: 'collector',
        accessName: 'RS485 / Modbus 采集',
        connectionHint: '映射 level、percent、alarmFlag 和 commStatus。',
        requirements: ['准备寄存器表', '确认量程', '确认安装基准'],
      },
      {
        brand: '海为 HaiWell',
        models: ['LoRa 液位终端', '4G 液位采集器', 'NB-IoT 液位计'],
        note: '适合分散井室和水箱液位监测。',
        accessMode: 'direct',
        accessName: 'MQTT / NB-IoT 直连',
        connectionHint: '映射液位、百分比、电池和信号字段。',
        requirements: ['准备设备认证', '确认上报周期', '确认安装基准'],
      },
      {
        brand: '铭控',
        models: ['MD-S280 液位变送器', 'MD-S271 液位计'],
        note: '适合工业水池和储罐液位采集。',
        accessMode: 'collector',
        accessName: 'Modbus 采集',
        connectionHint: '按量程映射液位和状态字。',
        requirements: ['确认量程', '准备寄存器表', '确认供电'],
      },
    ],
    modelKeywords: ['液位', '水箱', '集水井', '储罐', '污水池'],
    deviceType: '直连设备',
    sourceProduct: '液位传感器产品模板',
    accessModes: ['direct', 'collector'],
    accessName: '液位传感器接入',
    connectionHint: '按安装基准映射液位高度、百分比、报警位和通讯状态。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'telemetry', key: 'level', name: '液位高度', desc: '当前液位高度。', isKeyMetric: true },
      { kind: 'telemetry', key: 'percent', name: '液位百分比', desc: '按量程折算的液位百分比。', isKeyMetric: true },
      { kind: 'status', key: 'alarmFlag', name: '报警状态', desc: '高液位、低液位、传感器故障。' },
    ],
    requirements: ['确认量程和安装基准', '设备已联网或采集器已连通', '准备液位测试样例'],
    testSteps: ['读取液位高度', '核对百分比', '触发高液位样例', '读取通讯状态'],
    projectDefaults: ['创建设备档案', '启用高低液位告警', '生成液位趋势'],
    faultCodeDict: [
      {
        code: 'LV01',
        protocolField: 'alarm_flag',
        name: '液位越限',
        severity: 'critical',
        cause: '液位高于或低于安全范围，可能来自排水不畅、补水异常、探头遮挡或基准配置错误。',
        recommendedAction: '现场确认实际液位；核对安装基准和量程，必要时清理探头周边。',
        knowledgeRefs: ['kb-level-sensor'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'percent', name: '液位百分比', min: 20, max: 85, typicalAvg: 55, unit: '%', hint: '安全范围需按容器和业务场景调整。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-level-sensor',
        title: '液位传感器安装基准',
        body: '液位值依赖安装基准和量程配置。接入后需用现场实测值校验零点、满量程和百分比换算。',
        tags: ['液位', '量程', '安装'],
      },
    ],
  },
  {
    id: 'pressure-transmitter',
    name: '压力变送器',
    summary: '单个压力采集终端，用于管网、泵房、气瓶间、工艺管线和消防水压监测。',
    category: 'industrial',
    scenarios: ['industrial-collect', 'fire-safety', 'chemical-safety'],
    industries: ['manufacturing', 'water', 'building', 'chemical', 'energy', 'park'],
    supportedBrands: ['铭控', '通用 Modbus 仪表', '霍尼韦尔'],
    supportedModels: [
      {
        brand: '铭控',
        models: ['MD-S260 压力变送器', 'MD-S280 智能压力表', 'MD-S270 无线压力表'],
        note: '适合管网、泵房和工艺管线压力采集。',
        accessMode: 'collector',
        accessName: 'RS485 / Modbus 采集',
        connectionHint: '读取 pressure、temperature、alarmFlag 和 commStatus。',
        requirements: ['确认量程', '准备寄存器表', '确认供电和接线'],
      },
      {
        brand: '通用 Modbus 仪表',
        models: ['压力变送器', '智能压力表', '差压变送器'],
        note: '适合多厂家压力终端统一接入。',
        accessMode: 'collector',
        accessName: '通用 Modbus 采集',
        connectionHint: '按量程映射压力值、温度补偿和报警位。',
        requirements: ['确认量程', '准备寄存器表', '确认单位'],
      },
      {
        brand: '霍尼韦尔',
        models: ['ST700 Pressure Transmitter', 'STD700 Differential Pressure'],
        note: '适合工艺管线和高可靠压力监测。',
        accessMode: 'collector',
        accessName: '工业采集器映射',
        connectionHint: '通过采集器同步压力、状态字和诊断位。',
        requirements: ['准备设备参数', '确认采集链路', '确认量程'],
      },
    ],
    modelKeywords: ['压力', '差压', '管网', '水压', '气压'],
    deviceType: '子设备',
    sourceProduct: '压力变送器产品模板',
    accessModes: ['collector'],
    accessName: '压力变送器接入',
    connectionHint: '通过采集器映射压力值、状态字、报警位和通讯状态。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'telemetry', key: 'pressure', name: '压力', desc: '实时压力值。', isKeyMetric: true },
      { kind: 'telemetry', key: 'temperature', name: '介质温度', desc: '部分压力终端提供温度补偿。' },
      { kind: 'status', key: 'alarmFlag', name: '报警状态', desc: '高压、低压、传感器故障。', isKeyMetric: true },
      { kind: 'status', key: 'commStatus', name: '通讯状态', desc: '正常、超时、校验失败。' },
    ],
    requirements: ['确认量程和单位', '采集器已连通', '准备寄存器表'],
    testSteps: ['读取压力值', '核对量程换算', '触发越限样例', '模拟通讯异常'],
    projectDefaults: ['创建设备档案', '启用压力越限告警', '生成压力趋势'],
    faultCodeDict: [
      {
        code: 'PR01',
        protocolField: 'alarm_flag',
        name: '压力越限',
        severity: 'critical',
        cause: '压力超过模板安全范围，可能来自阀门状态变化、管路堵塞、泄漏或量程配置错误。',
        recommendedAction: '现场确认压力表读数和阀门状态；核对量程、单位和采集倍率。',
        knowledgeRefs: ['kb-pressure'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'pressure', name: '压力', min: 0.2, max: 0.8, typicalAvg: 0.45, unit: 'MPa', hint: '默认按楼宇水压示例，项目内需按管网类型调整。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-pressure',
        title: '压力变送器量程校验',
        body: '压力类终端接入后必须核对单位、量程和倍率。kPa、bar、MPa 混用会造成告警阈值明显偏差。',
        tags: ['压力', '量程', 'Modbus'],
      },
    ],
  },
  {
    id: 'vibration-sensor',
    name: '振动传感器',
    summary: '单个三轴振动采集终端，用于电机、泵、风道支架、输送线和旋转部件状态监测。',
    category: 'industrial',
    scenarios: ['industrial-collect', 'environment'],
    industries: ['manufacturing', 'water', 'building', 'energy', 'park'],
    supportedBrands: ['通用 MQTT 传感器', '通用 Modbus 仪表', '海为 HaiWell'],
    supportedModels: [
      {
        brand: '通用 MQTT 传感器',
        models: ['无线振动传感器', '三轴振动终端', '4G 振动采集器'],
        note: '适合分散旋转部件的趋势采集。',
        accessMode: 'direct',
        accessName: 'MQTT 直连',
        connectionHint: '映射 vibrationX、vibrationY、vibrationZ、temperature 和 battery。',
        requirements: ['确认采样周期', '准备设备认证', '确认安装方向'],
      },
      {
        brand: '通用 Modbus 仪表',
        models: ['振动变送器', '三轴振动采集终端', '轴承振动传感器'],
        note: '适合通过采集器接入的工业振动点位。',
        accessMode: 'collector',
        accessName: 'RS485 / Modbus 采集',
        connectionHint: '按寄存器表同步振动速度、加速度和温度。',
        requirements: ['准备寄存器表', '确认采样周期', '确认量程'],
      },
      {
        brand: '海为 HaiWell',
        models: ['LoRa 振动终端', '边缘振动采集终端'],
        note: '适合低频巡检型振动趋势监测。',
        accessMode: 'edge',
        accessName: '网关映射',
        connectionHint: '网关同步振动峰值、温度、电池和信号。',
        requirements: ['子设备已入网', '确认安装方向', '确认上报周期'],
      },
    ],
    modelKeywords: ['振动', '三轴', '电机', '泵', '轴承', '旋转部件'],
    deviceType: '直连设备',
    sourceProduct: '振动传感器产品模板',
    accessModes: ['direct', 'collector', 'edge'],
    accessName: '振动传感器接入',
    connectionHint: '按终端类型映射振动、温度、电池、信号和通讯状态。',
    maintainedBy: 'partner',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'telemetry', key: 'vibration', name: '振动速度', desc: '振动速度有效值或峰值。', isKeyMetric: true },
      { kind: 'telemetry', key: 'acceleration', name: '加速度', desc: '三轴加速度或合成值。', isKeyMetric: true },
      { kind: 'telemetry', key: 'temperature', name: '表面温度', desc: '传感器或安装面温度。' },
      { kind: 'status', key: 'alarmFlag', name: '报警状态', desc: '振动越限、温度越限、设备离线。' },
    ],
    requirements: ['确认安装方向和采样周期', '设备已联网或采集器已连通', '准备基线样例'],
    testSteps: ['读取振动值', '读取温度', '校验采样周期', '触发越限样例'],
    projectDefaults: ['创建设备档案', '生成振动趋势', '启用振动 / 温度越限告警'],
    faultCodeDict: [
      {
        code: 'VB01',
        protocolField: 'alarm_flag',
        name: '振动越限',
        severity: 'warning',
        cause: '振动值超过模板范围，可能来自安装松动、轴承异常、负载变化或传感器方向配置错误。',
        recommendedAction: '先核对安装紧固和方向；持续升高时安排现场巡检。',
        knowledgeRefs: ['kb-vibration'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'vibration', name: '振动速度', min: 0, max: 4.5, typicalAvg: 1.8, unit: 'mm/s', hint: '默认参考轻载旋转部件，需按设备类型建立基线。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-vibration',
        title: '振动传感器基线建立',
        body: '振动监测应先建立稳定运行基线，再做趋势偏离判断。单次峰值需要结合负载和运行状态确认。',
        tags: ['振动', '基线', '预测维护'],
      },
    ],
  },
  {
    id: 'static-grounding-monitor',
    name: '静电接地监测器',
    summary: '单个静电接地状态监测终端，用于卸油区、装卸区、危化暂存点和防爆作业点。',
    category: 'industrial',
    scenarios: ['fuel-safety', 'chemical-safety', 'industrial-collect'],
    industries: ['energy', 'chemical', 'manufacturing', 'park', 'security'],
    supportedBrands: ['通用 Modbus 仪表', '汉威科技', '海为 HaiWell'],
    supportedModels: [
      {
        brand: '通用 Modbus 仪表',
        models: ['静电接地报警器', '防爆接地监测终端', '接地电阻监测器'],
        note: '适合油气和危化装卸作业接地状态采集。',
        accessMode: 'collector',
        accessName: 'RS485 / Modbus 采集',
        connectionHint: '映射 groundingStatus、resistance、alarmFlag 和 commStatus。',
        requirements: ['准备寄存器表', '确认防爆要求', '确认接地夹状态字段'],
      },
      {
        brand: '汉威科技',
        models: ['防爆静电接地报警器', '接地状态监测终端'],
        note: '适合加油和危化作业点接地监测。',
        accessMode: 'collector',
        accessName: '安全采集器映射',
        connectionHint: '同步接地电阻、夹持状态和报警输出。',
        requirements: ['准备采集点表', '确认报警输出', '完成现场测试'],
      },
      {
        brand: '海为 HaiWell',
        models: ['4G 接地监测终端', 'LoRa 接地状态终端'],
        note: '适合分散作业点直连接入。',
        accessMode: 'direct',
        accessName: 'MQTT 直连',
        connectionHint: '映射 groundingStatus、resistance 和 alarmFlag。',
        requirements: ['准备设备认证', '确认上报周期', '确认现场测试方法'],
      },
    ],
    modelKeywords: ['静电接地', '接地电阻', '卸油区', '防爆', '装卸'],
    deviceType: '直连设备',
    sourceProduct: '静电接地监测器产品模板',
    accessModes: ['direct', 'collector'],
    accessName: '静电接地监测器接入',
    connectionHint: '按接地终端字段映射接地状态、电阻值、报警位和通讯状态。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'status', key: 'groundingStatus', name: '接地状态', desc: '已接地、未接地、夹持异常。', isKeyMetric: true },
      { kind: 'telemetry', key: 'resistance', name: '接地电阻', desc: '接地回路电阻值。', isKeyMetric: true },
      { kind: 'status', key: 'alarmFlag', name: '报警状态', desc: '接地异常、通讯异常、设备故障。' },
    ],
    requirements: ['确认防爆和安装要求', '设备已联网或采集器已连通', '准备接地测试样例'],
    testSteps: ['读取接地状态', '读取电阻值', '断开接地夹触发报警', '恢复后校验事件'],
    projectDefaults: ['创建设备档案', '启用接地异常告警', '生成作业安全状态卡'],
    faultCodeDict: [
      {
        code: 'SG01',
        protocolField: 'grounding_status',
        name: '接地异常',
        severity: 'critical',
        cause: '接地夹未连接、接地电阻过高、回路断线或终端故障。',
        recommendedAction: '暂停相关作业并现场确认接地夹、接地点和线缆状态。',
        knowledgeRefs: ['kb-grounding'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'resistance', name: '接地电阻', min: 0, max: 10, typicalAvg: 2, unit: 'Ω', hint: '具体阈值需按现场安全规范配置。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-grounding',
        title: '静电接地监测处置',
        body: '接地异常属于作业安全事件，处理顺序应先停作业、再查线缆和接地点，最后复核设备状态。',
        tags: ['静电接地', '防爆', '安全'],
      },
    ],
  },
  {
    id: 'door-contact-sensor',
    name: '门磁传感器',
    summary: '单个门窗开合状态终端，用于机房门、弱电间、库房、康养房间和设备间入口。',
    category: 'sensor',
    scenarios: ['access-control', 'data-center', 'care-assist'],
    industries: ['building', 'commercial', 'care', 'data-center', 'security', 'park'],
    supportedBrands: ['通用 Zigbee 传感器', '通用 MQTT 传感器', '海为 HaiWell'],
    supportedModels: [
      {
        brand: '通用 Zigbee 传感器',
        models: ['Zigbee 门磁', 'LoRa 门磁', 'BLE 门磁标签'],
        note: '适合房间级低功耗开合状态监测。',
        accessMode: 'edge',
        accessName: '低功耗网关映射',
        connectionHint: '网关同步 openState、battery、tamper 和 signal。',
        requirements: ['子设备已入网', '确认安装位置', '确认电池周期'],
      },
      {
        brand: '通用 MQTT 传感器',
        models: ['Wi-Fi 门磁', 'NB-IoT 门磁', '4G 门磁终端'],
        note: '适合分散门点直连接入。',
        accessMode: 'direct',
        accessName: '通用 MQTT Topic 映射',
        connectionHint: '映射开合状态、低电量、拆卸和心跳。',
        requirements: ['准备设备认证', '确认 Topic 格式', '完成门点登记'],
      },
      {
        brand: '海为 HaiWell',
        models: ['LoRa 门磁终端', 'Zigbee 门磁传感器'],
        note: '适合机房、库房和康养房间门点。',
        accessMode: 'edge',
        accessName: '网关映射',
        connectionHint: '先入网再同步开合状态、电池和拆卸事件。',
        requirements: ['子设备已入网', '确认门点编号', '准备测试样例'],
      },
    ],
    modelKeywords: ['门磁', '开门', '关门', '拆卸', '低电量'],
    deviceType: '子设备',
    sourceProduct: '门磁传感器产品模板',
    accessModes: ['direct', 'edge'],
    accessName: '门磁传感器接入',
    connectionHint: '按门点映射开合状态、电池、拆卸和信号字段。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'status', key: 'openState', name: '开合状态', desc: '打开、关闭、长开。', isKeyMetric: true },
      { kind: 'telemetry', key: 'battery', name: '电池电压', desc: '门磁电池状态。', isKeyMetric: true },
      { kind: 'status', key: 'tamper', name: '拆卸状态', desc: '外壳打开或安装异常。' },
      { kind: 'alarm', key: 'alarm', name: '门点告警', desc: '长开、非法打开、低电量和拆卸告警。' },
    ],
    requirements: ['完成门点登记', '设备已入网或已写入平台地址', '准备开合测试样例'],
    testSteps: ['读取当前开合状态', '开门触发事件', '关门触发恢复', '校验电池字段'],
    projectDefaults: ['创建设备档案', '启用长开 / 非法打开告警', '生成门点状态卡'],
    faultCodeDict: [
      {
        code: 'DC01',
        protocolField: 'open_state',
        name: '门长开',
        severity: 'warning',
        cause: '门点持续打开超过策略时间，可能来自人员未关门、磁铁位置偏移或设备误报。',
        recommendedAction: '先确认现场门状态，再检查磁铁安装位置和电池电压。',
        knowledgeRefs: ['kb-door-contact'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'battery', name: '电池电压', min: 2.8, max: 3.6, typicalAvg: 3.2, unit: 'V', hint: '低于 2.8V 建议更换。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-door-contact',
        title: '门磁安装检查',
        body: '门磁误报多来自磁铁间距过大、安装面晃动或电池电压不足。安装后应做开关门事件测试。',
        tags: ['门磁', '安防', '安装'],
      },
    ],
  },
  {
    id: 'presence-radar-sensor',
    name: '毫米波存在传感器',
    summary: '单个存在感知终端，用于康养房间、卫生间、值班室和人员滞留风险监测点位。',
    category: 'sensor',
    scenarios: ['care-assist', 'environment', 'commercial-ops'],
    industries: ['care', 'building', 'commercial', 'park', 'security'],
    supportedBrands: ['通用 MQTT 传感器', '通用 Zigbee 传感器', '海为 HaiWell'],
    supportedModels: [
      {
        brand: '通用 MQTT 传感器',
        models: ['毫米波存在传感器', '跌倒感知雷达', '离床感知终端'],
        note: '适合康养房间和卫生间无图像感知场景。',
        accessMode: 'direct',
        accessName: 'MQTT 直连',
        connectionHint: '映射 presence、motion、fallFlag、battery 和 signal。',
        requirements: ['确认安装高度', '准备设备认证', '完成房间点位登记'],
      },
      {
        brand: '通用 Zigbee 传感器',
        models: ['Zigbee 存在传感器', 'BLE 存在标签', 'LoRa 人体存在终端'],
        note: '适合低功耗房间级存在感知。',
        accessMode: 'edge',
        accessName: '低功耗网关映射',
        connectionHint: '先入网再同步存在状态、电池和信号。',
        requirements: ['子设备已入网', '确认感知区域', '确认上报周期'],
      },
      {
        brand: '海为 HaiWell',
        models: ['LoRa 存在感知终端', 'Wi-Fi 毫米波传感器'],
        note: '适合值班室、活动室和康养房间点位。',
        accessMode: 'direct',
        accessName: 'MQTT / LoRa 网关接入',
        connectionHint: '按设备模式映射存在、移动和离床状态。',
        requirements: ['确认设备模式', '准备字段样例', '完成位置登记'],
      },
    ],
    modelKeywords: ['毫米波', '存在', '离床', '跌倒', '滞留', '康养'],
    deviceType: '直连设备',
    sourceProduct: '毫米波存在传感器产品模板',
    accessModes: ['direct', 'edge'],
    accessName: '毫米波存在传感器接入',
    connectionHint: '按设备能力映射存在、移动、离床、跌倒、电池和信号字段。',
    maintainedBy: 'partner',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'status', key: 'presence', name: '存在状态', desc: '有人、无人、静止存在。', isKeyMetric: true },
      { kind: 'status', key: 'motion', name: '活动状态', desc: '静止、移动、离开。', isKeyMetric: true },
      { kind: 'alarm', key: 'fallFlag', name: '跌倒 / 滞留告警', desc: '跌倒、滞留、离床等事件。' },
      { kind: 'telemetry', key: 'battery', name: '电池电压', desc: '低功耗设备电池状态。' },
    ],
    requirements: ['确认安装高度和感知区域', '设备已联网或已入网', '准备场景测试样例'],
    testSteps: ['读取存在状态', '模拟进入离开', '触发滞留样例', '读取电池或信号字段'],
    projectDefaults: ['创建设备档案', '启用滞留 / 离床 / 跌倒告警', '生成房间感知卡'],
    faultCodeDict: [
      {
        code: 'PRD01',
        protocolField: 'presence_state',
        name: '长时间无活动',
        severity: 'warning',
        cause: '存在状态持续但活动状态长期不变，可能来自人员静止、感知区域遮挡或设备安装角度不合适。',
        recommendedAction: '按康养流程先确认人员安全，再检查安装角度和感知区域。',
        knowledgeRefs: ['kb-presence-radar'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'battery', name: '电池电压', min: 2.8, max: 3.6, typicalAvg: 3.2, unit: 'V', hint: '低功耗终端低于 2.8V 建议更换。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-presence-radar',
        title: '毫米波存在传感器布点',
        body: '毫米波存在传感器应避开强金属遮挡和频繁摆动区域。康养场景需先确认隐私边界和告警处置流程。',
        tags: ['毫米波', '康养', '布点'],
      },
    ],
  },
  {
    id: 'emergency-button',
    name: '紧急按钮',
    summary: '单个手动触发终端，用于服务台、康养房间、卫生间、值班岗亭和高风险作业点。',
    category: 'sensor',
    scenarios: ['care-assist', 'fire-safety', 'access-control', 'commercial-ops'],
    industries: ['care', 'commercial', 'building', 'park', 'security'],
    supportedBrands: ['通用 Zigbee 传感器', '通用 MQTT 传感器', '海为 HaiWell'],
    supportedModels: [
      {
        brand: '通用 Zigbee 传感器',
        models: ['Zigbee 紧急按钮', 'LoRa 求助按钮', 'BLE 求助按钮'],
        note: '适合房间、卫生间和值班岗亭低功耗求助点位。',
        accessMode: 'edge',
        accessName: '低功耗网关映射',
        connectionHint: '网关同步 pressEvent、battery、tamper 和 signal。',
        requirements: ['子设备已入网', '确认安装位置', '确认电池周期'],
      },
      {
        brand: '通用 MQTT 传感器',
        models: ['Wi-Fi 紧急按钮', 'NB-IoT 求助按钮', '4G 紧急终端'],
        note: '适合分散求助点位直连接入。',
        accessMode: 'direct',
        accessName: 'MQTT 直连',
        connectionHint: '映射按下、复位、低电量和心跳事件。',
        requirements: ['准备设备认证', '确认 Topic 格式', '完成点位登记'],
      },
      {
        brand: '海为 HaiWell',
        models: ['LoRa 紧急按钮', 'NB-IoT 求助终端'],
        note: '适合康养和商业服务点位。',
        accessMode: 'direct',
        accessName: 'MQTT / LoRa 网关接入',
        connectionHint: '按设备模式映射求助事件、电池和信号。',
        requirements: ['准备设备认证或网关编号', '确认安装位置', '准备测试样例'],
      },
    ],
    modelKeywords: ['紧急按钮', '求助', 'SOS', '手动报警', '复位'],
    deviceType: '直连设备',
    sourceProduct: '紧急按钮产品模板',
    accessModes: ['direct', 'edge'],
    accessName: '紧急按钮接入',
    connectionHint: '映射按下、复位、拆卸、低电量和信号字段。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'telemetry', 'event', 'alarm'],
    dataPoints: [
      { kind: 'event', key: 'pressEvent', name: '按下事件', desc: '短按、长按、双击或求助触发。', isKeyMetric: true },
      { kind: 'status', key: 'resetState', name: '复位状态', desc: '待处理、已复位。', isKeyMetric: true },
      { kind: 'telemetry', key: 'battery', name: '电池电压', desc: '低功耗终端电池状态。' },
      { kind: 'alarm', key: 'alarm', name: '求助告警', desc: '紧急求助、低电量、拆卸和离线。' },
    ],
    requirements: ['完成点位登记和处置对象配置', '设备已入网或已写入平台地址', '准备求助测试样例'],
    testSteps: ['读取心跳', '按下按钮触发事件', '复位按钮', '校验低电量字段'],
    projectDefaults: ['创建设备档案', '启用求助告警', '生成处置通知卡'],
    faultCodeDict: [
      {
        code: 'EB01',
        protocolField: 'press_event',
        name: '紧急求助触发',
        severity: 'critical',
        cause: '按钮被按下，可能来自真实求助、演练测试或误触。',
        recommendedAction: '按项目处置流程通知人员现场确认；确认误触后记录原因并复位。',
        knowledgeRefs: ['kb-emergency-button'],
      },
    ],
    telemetryNormalRanges: [
      { pointKey: 'battery', name: '电池电压', min: 2.8, max: 3.6, typicalAvg: 3.2, unit: 'V', hint: '低于 2.8V 建议更换。' },
    ],
    knowledgeBase: [
      {
        id: 'kb-emergency-button',
        title: '紧急按钮演练校验',
        body: '紧急按钮接入后应定期做演练测试，确认事件、通知对象、复位动作和处置记录都能闭环。',
        tags: ['求助', '演练', '康养'],
      },
    ],
  },
  {
    id: 'access-controller',
    name: '门禁控制器',
    summary: '单个门禁控制终端，用于门点身份核验、开门事件、门锁状态和异常通行事件接入。',
    category: 'integration',
    scenarios: ['access-control', 'data-center', 'commercial-ops'],
    industries: ['building', 'commercial', 'park', 'data-center', 'security'],
    supportedBrands: ['海康威视门禁', '大华门禁', '通用门禁控制器'],
    supportedModels: [
      {
        brand: '海康威视门禁',
        models: ['DS-K2601', 'DS-K1T 系列门禁终端', 'DS-K2804'],
        note: '适合门点开门事件和门锁状态接入。',
        accessMode: 'third-party',
        accessName: '门禁事件 API 接入',
        connectionHint: '同步人员通行事件、门状态、告警事件和设备在线状态。',
        requirements: ['准备平台地址和授权', '确认门点编号', '确认事件订阅'],
      },
      {
        brand: '大华门禁',
        models: ['ASC1204B', 'ASI 系列门禁终端', 'ASC2204C'],
        note: '适合多门点控制器事件同步。',
        accessMode: 'third-party',
        accessName: '门禁平台同步',
        connectionHint: '通过平台接口同步开门、拒绝、门未关和设备状态。',
        requirements: ['准备接口授权', '确认门点映射', '准备事件样例'],
      },
      {
        brand: '通用门禁控制器',
        models: ['TCP/IP 门禁控制器', '单门门禁控制器', '四门门禁控制器'],
        note: '适合标准门禁事件和状态接入。',
        accessMode: 'collector',
        accessName: '事件网关 / Modbus 采集',
        connectionHint: '按门点映射门状态、继电器状态和通行事件。',
        requirements: ['确认通讯协议', '准备门点表', '确认事件字段'],
      },
    ],
    modelKeywords: ['门禁', '开门事件', '门锁', '通行', '刷卡'],
    deviceType: '直连设备',
    sourceProduct: '门禁控制器产品模板',
    accessModes: ['third-party', 'collector'],
    accessName: '门禁控制器接入',
    connectionHint: '按门点映射通行事件、门状态、门锁状态和设备在线状态。',
    maintainedBy: 'partner',
    readiness: 'ready',
    dataKinds: ['status', 'event', 'command', 'alarm'],
    dataPoints: [
      { kind: 'event', key: 'accessEvent', name: '通行事件', desc: '开门、拒绝、远程开门、按钮开门。', isKeyMetric: true },
      { kind: 'status', key: 'doorState', name: '门状态', desc: '打开、关闭、长开、异常。', isKeyMetric: true },
      { kind: 'status', key: 'lockState', name: '门锁状态', desc: '上锁、解锁、故障。' },
      { kind: 'command', key: 'remoteOpen', name: '远程开门', desc: '远程开门或解除锁定命令。' },
      { kind: 'alarm', key: 'alarm', name: '通行告警', desc: '门未关、非法开门、胁迫、设备离线。' },
    ],
    requirements: ['确认门点编号和授权范围', '准备事件样例', '确认远程命令权限'],
    testSteps: ['同步门点列表', '触发刷卡开门事件', '读取门状态', '校验门未关告警'],
    projectDefaults: ['创建设备档案', '启用门未关 / 非法开门告警', '生成门点通行记录'],
    faultCodeDict: [
      {
        code: 'AC01',
        protocolField: 'door_state',
        name: '门未关',
        severity: 'warning',
        cause: '门点持续打开超过策略时间，可能来自人员未关门、门锁故障或门磁状态异常。',
        recommendedAction: '现场确认门状态和门锁；必要时联动通知安保人员。',
        knowledgeRefs: ['kb-access-controller'],
      },
    ],
    telemetryNormalRanges: [],
    knowledgeBase: [
      {
        id: 'kb-access-controller',
        title: '门禁控制器事件接入',
        body: '门禁接入需确认门点编号、事件类型和远程命令权限。门未关类告警应同时核对门磁和门锁状态。',
        tags: ['门禁', '通行', '事件'],
      },
    ],
  },
  {
    id: 'io-relay-controller',
    name: 'IO 继电器控制器',
    summary: '单个数字量输入输出终端，用于声光提示、阀位反馈、干接点采集和简单联动控制。',
    category: 'industrial',
    scenarios: ['industrial-collect', 'fire-safety', 'fuel-safety', 'system-sync'],
    industries: ['building', 'commercial', 'park', 'manufacturing', 'chemical', 'energy'],
    supportedBrands: ['海为 HaiWell', '通用 Modbus 仪表', '西门子'],
    supportedModels: [
      {
        brand: '海为 HaiWell',
        models: ['C16S2R', 'C10S0R', '4G IO 控制器'],
        note: '适合干接点采集、继电器输出和简单联动。',
        accessMode: 'direct',
        accessName: 'MQTT / Modbus 直连',
        connectionHint: '映射 di1-di16、do1-do8、relayStatus 和 deviceStatus。',
        requirements: ['确认输入输出点表', '准备设备认证', '确认联动权限'],
      },
      {
        brand: '通用 Modbus 仪表',
        models: ['8DI8DO 控制器', '16DI 采集模块', '继电器输出模块'],
        note: '适合通过采集器统一接入的数字量点位。',
        accessMode: 'collector',
        accessName: 'RS485 / Modbus 采集',
        connectionHint: '按点表映射数字量输入、输出和通讯状态。',
        requirements: ['准备寄存器表', '确认点位命名', '确认输出安全策略'],
      },
      {
        brand: '西门子',
        models: ['LOGO! 8', 'S7-1200 DI/DO 模块'],
        note: '适合标准控制器的状态采集和受控输出。',
        accessMode: 'collector',
        accessName: '工业采集器映射',
        connectionHint: '通过采集器同步输入输出状态，命令需按白名单启用。',
        requirements: ['准备点表', '确认通讯链路', '确认命令白名单'],
      },
    ],
    modelKeywords: ['IO', 'DI', 'DO', '继电器', '干接点', '联动'],
    deviceType: '直连设备',
    sourceProduct: 'IO 继电器控制器产品模板',
    accessModes: ['direct', 'collector'],
    accessName: 'IO 继电器控制器接入',
    connectionHint: '按点表映射数字量输入、输出状态、命令白名单和通讯状态。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'event', 'command', 'alarm'],
    dataPoints: [
      { kind: 'status', key: 'diStatus', name: '输入状态', desc: '数字量输入点状态。', isKeyMetric: true },
      { kind: 'status', key: 'doStatus', name: '输出状态', desc: '数字量输出或继电器状态。', isKeyMetric: true },
      { kind: 'command', key: 'relayCommand', name: '继电器控制', desc: '受控输出命令，需启用白名单。' },
      { kind: 'alarm', key: 'alarm', name: '模块告警', desc: '通讯异常、输出失败、设备离线。' },
    ],
    requirements: ['确认点表和命令白名单', '设备已联网或采集器已连通', '完成输出安全确认'],
    testSteps: ['读取输入状态', '读取输出状态', '执行一次安全输出测试', '模拟通讯异常'],
    projectDefaults: ['创建设备档案', '启用通讯异常和输出失败告警', '生成 IO 点位卡'],
    faultCodeDict: [
      {
        code: 'IO01',
        protocolField: 'command_result',
        name: '输出命令失败',
        severity: 'warning',
        cause: '继电器输出未按预期变化，可能来自命令未授权、设备离线、线路断开或输出保护。',
        recommendedAction: '核对命令白名单和联动策略；现场确认输出回路和设备在线状态。',
        knowledgeRefs: ['kb-io-relay'],
      },
    ],
    telemetryNormalRanges: [],
    knowledgeBase: [
      {
        id: 'kb-io-relay',
        title: 'IO 控制器安全启用',
        body: 'IO 输出涉及现场动作，默认只读输入状态。启用输出命令前需要配置白名单、确认回路用途并做现场测试。',
        tags: ['IO', '继电器', '命令'],
      },
    ],
  },
  {
    id: 'network-camera',
    name: '网络摄像机',
    summary: '单个视频采集终端，可通过 GB28181、ONVIF 或厂商接口接入，用于视频预览、抓拍、云台控制和在线状态管理。',
    category: 'video',
    scenarios: ['video-inspection', 'access-control', 'fire-safety', 'commercial-ops'],
    industries: ['security', 'commercial', 'park', 'building', 'care', 'energy'],
    supportedBrands: ['海康威视', '大华', '宇视', '通用 ONVIF 摄像机'],
    supportedModels: [
      {
        brand: '海康威视',
        models: ['DS-2CD3T 系列', 'DS-2DE7 球机', 'DS-2CD7 智能摄像机'],
        note: '适合固定枪机、球机和智能摄像机接入。',
        accessMode: 'gb28181',
        accessName: 'GB28181 设备注册',
        connectionHint: '摄像机或平台网关向国标服务注册，映射设备编码、通道编码、在线状态和码流地址。',
        requirements: ['准备 SIP 设备编码', '确认国标域和密码', '确认主子码流地址'],
      },
      {
        brand: '大华',
        models: ['DH-IPC-HFW 系列', 'DH-SD 球机', 'DH-IPC-HDBW 系列'],
        note: '适合园区、商业和楼宇视频点位。',
        accessMode: 'gb28181',
        accessName: 'GB28181 设备注册',
        connectionHint: '注册后同步目录、通道、在线状态、云台能力和录像能力。',
        requirements: ['准备设备编码', '确认平台注册参数', '确认网络可达'],
      },
      {
        brand: '宇视',
        models: ['IPC-B 系列', 'IPC-S 系列', 'HIC 系列'],
        note: '适合多品牌视频点位统一接入。',
        accessMode: 'gb28181',
        accessName: 'GB28181 设备注册',
        connectionHint: '按国标目录同步通道和设备状态，保留厂商型号作为资产标签。',
        requirements: ['准备 SIP 参数', '确认通道编码', '确认取流方式'],
      },
      {
        brand: '通用 ONVIF 摄像机',
        models: ['ONVIF Profile S 摄像机', 'ONVIF Profile T 摄像机', 'RTSP 网络摄像机'],
        note: '适合非国标摄像机或内网直接管理场景。',
        accessMode: 'third-party',
        accessName: 'ONVIF / RTSP 接入',
        connectionHint: '通过 ONVIF 发现设备、读取能力、同步码流地址和云台能力。',
        requirements: ['准备设备地址和账号', '确认 ONVIF 已开启', '确认 RTSP 地址可用'],
      },
    ],
    modelKeywords: ['摄像机', 'IPC', 'GB28181', 'ONVIF', 'RTSP', '云台', '抓拍'],
    deviceType: '直连设备',
    sourceProduct: '网络摄像机产品模板',
    accessModes: ['gb28181', 'third-party'],
    accessName: '网络摄像机接入',
    connectionHint: '通过 GB28181 或 ONVIF 接入，映射在线状态、通道、码流、云台能力和告警事件。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'event', 'command', 'video', 'alarm'],
    dataPoints: [
      { kind: 'video', key: 'liveStream', name: '实时码流', desc: '主码流、子码流、取流地址和播放状态。', isKeyMetric: true },
      { kind: 'status', key: 'onlineState', name: '在线状态', desc: '在线、离线、注册中、取流失败。', isKeyMetric: true },
      { kind: 'command', key: 'ptzControl', name: '云台控制', desc: '上、下、左、右、缩放、预置位。' },
      { kind: 'event', key: 'snapshotEvent', name: '抓拍事件', desc: '手动抓拍、规则抓拍和预览截图。' },
      { kind: 'alarm', key: 'deviceAlarm', name: '设备告警', desc: '遮挡、移动侦测、视频丢失和设备离线。' },
    ],
    requirements: ['确认 GB28181 或 ONVIF 接入方式', '准备设备编码、账号或取流参数', '确认网络、端口和码流可达'],
    testSteps: ['注册设备或发现设备', '读取在线状态', '拉取实时码流', '执行抓拍或云台测试'],
    projectDefaults: ['创建设备档案', '生成视频资源通道', '启用离线 / 取流失败告警'],
    faultCodeDict: [
      {
        code: 'VC01',
        protocolField: 'online_state',
        name: '摄像机离线',
        severity: 'critical',
        cause: '设备未注册、网络不可达、认证失败、国标参数错误或摄像机断电。',
        recommendedAction: '先确认设备供电和网络，再核对 GB28181 / ONVIF 参数、账号和端口。',
        knowledgeRefs: ['kb-network-camera'],
      },
      {
        code: 'VC11',
        protocolField: 'stream_state',
        name: '取流失败',
        severity: 'warning',
        cause: '码流地址不可达、账号权限不足、转码资源不足或设备主子码流配置异常。',
        recommendedAction: '用原厂工具验证取流地址；必要时切换子码流或调整码率。',
        knowledgeRefs: ['kb-camera-stream'],
      },
    ],
    telemetryNormalRanges: [],
    knowledgeBase: [
      {
        id: 'kb-network-camera',
        title: '摄像机接入参数检查',
        body: 'GB28181 接入重点检查 SIP 编码、域、密码、端口和心跳；ONVIF 接入重点检查账号、时间同步和服务发现。',
        tags: ['摄像机', 'GB28181', 'ONVIF'],
      },
      {
        id: 'kb-camera-stream',
        title: '摄像机取流排查',
        body: '取流失败应先用原厂工具或标准播放器验证 RTSP / 国标取流，再排查平台转发、转码和网络策略。',
        tags: ['取流', 'RTSP', '视频'],
      },
    ],
  },
  {
    id: 'nvr-recorder',
    name: 'NVR',
    summary: '单个网络录像设备，可通过 GB28181、ONVIF 或厂商接口接入，用于通道目录、录像状态、存储状态和设备在线管理。',
    category: 'video',
    scenarios: ['video-inspection', 'access-control', 'commercial-ops', 'data-center'],
    industries: ['security', 'commercial', 'park', 'building', 'data-center', 'energy'],
    supportedBrands: ['海康威视', '大华', '宇视', '通用 GB28181 设备'],
    supportedModels: [
      {
        brand: '海康威视',
        models: ['DS-7600N 系列', 'DS-8600N 系列', 'iDS-9600NX 系列'],
        note: '适合通过 NVR 汇聚多路通道和录像状态。',
        accessMode: 'gb28181',
        accessName: 'GB28181 平台级联',
        connectionHint: 'NVR 向国标服务注册后同步目录、通道、录像状态和在线状态。',
        requirements: ['准备 SIP 设备编码', '确认通道编码规则', '确认录像回放权限'],
      },
      {
        brand: '大华',
        models: ['NVR4000 系列', 'NVR5000 系列', 'IVSS 系列'],
        note: '适合商业和园区 NVR 通道接入。',
        accessMode: 'gb28181',
        accessName: 'GB28181 平台级联',
        connectionHint: '同步通道树、实时预览、录像查询和设备告警。',
        requirements: ['准备国标参数', '确认通道目录', '确认回放接口'],
      },
      {
        brand: '宇视',
        models: ['NVR-B 系列', 'NVR-S 系列', 'VM 系列'],
        note: '适合多通道视频汇聚接入。',
        accessMode: 'gb28181',
        accessName: 'GB28181 平台级联',
        connectionHint: '按目录同步通道、录像能力、在线状态和告警事件。',
        requirements: ['准备 SIP 参数', '确认目录同步', '确认录像能力'],
      },
      {
        brand: '通用 GB28181 设备',
        models: ['国标 NVR', '国标视频网关', 'ONVIF NVR'],
        note: '适合标准协议的视频汇聚设备。',
        accessMode: 'third-party',
        accessName: 'GB28181 / ONVIF 汇聚接入',
        connectionHint: '同步通道目录、实时码流、录像状态、硬盘状态和设备告警。',
        requirements: ['确认协议版本', '准备设备账号或 SIP 参数', '确认网络端口'],
      },
    ],
    modelKeywords: ['NVR', '录像机', 'GB28181', 'ONVIF', '通道', '录像', '硬盘'],
    deviceType: '直连设备',
    sourceProduct: 'NVR 产品模板',
    accessModes: ['gb28181', 'third-party'],
    accessName: 'NVR 接入',
    connectionHint: '通过 GB28181 或 ONVIF 接入，映射通道目录、录像状态、存储状态和设备在线状态。',
    maintainedBy: 'official',
    readiness: 'ready',
    dataKinds: ['status', 'event', 'command', 'video', 'alarm'],
    dataPoints: [
      { kind: 'status', key: 'onlineState', name: '在线状态', desc: '在线、离线、注册中。', isKeyMetric: true },
      { kind: 'video', key: 'channelCatalog', name: '通道目录', desc: 'NVR 下挂通道、通道在线状态和通道码流。', isKeyMetric: true },
      { kind: 'status', key: 'recordState', name: '录像状态', desc: '录像中、未录像、回放可用性。', isKeyMetric: true },
      { kind: 'status', key: 'storageState', name: '存储状态', desc: '硬盘正常、满盘、损坏、未格式化。', isKeyMetric: true },
      { kind: 'command', key: 'recordQuery', name: '录像查询', desc: '按通道和时间查询录像片段。' },
      { kind: 'alarm', key: 'deviceAlarm', name: '设备告警', desc: '硬盘异常、录像异常、通道离线、设备离线。' },
    ],
    requirements: ['确认 GB28181 或 ONVIF 接入方式', '准备设备编码、账号或级联参数', '确认通道目录和录像权限'],
    testSteps: ['注册 NVR 或发现设备', '同步通道目录', '拉取通道实时码流', '查询一段录像'],
    projectDefaults: ['创建设备档案', '生成视频通道资源', '启用设备离线 / 通道离线 / 硬盘异常告警'],
    faultCodeDict: [
      {
        code: 'NVR01',
        protocolField: 'online_state',
        name: 'NVR 离线',
        severity: 'critical',
        cause: 'NVR 未注册、网络不可达、认证失败、国标参数错误或设备断电。',
        recommendedAction: '确认设备供电、网络和平台注册参数；同网段多设备异常时优先排查网络策略。',
        knowledgeRefs: ['kb-nvr-access'],
      },
      {
        code: 'NVR11',
        protocolField: 'storage_state',
        name: '存储异常',
        severity: 'warning',
        cause: '硬盘满盘、损坏、未格式化或录像计划异常。',
        recommendedAction: '检查硬盘状态和录像计划；确认回放查询权限和存储策略。',
        knowledgeRefs: ['kb-nvr-storage'],
      },
    ],
    telemetryNormalRanges: [],
    knowledgeBase: [
      {
        id: 'kb-nvr-access',
        title: 'NVR 国标级联检查',
        body: 'NVR 接入重点检查 SIP 编码、目录同步、心跳、通道编码和回放权限。目录能同步不代表码流一定可取。',
        tags: ['NVR', 'GB28181', '级联'],
      },
      {
        id: 'kb-nvr-storage',
        title: 'NVR 存储状态排查',
        body: '存储异常需要同时确认硬盘健康、录像计划、覆盖策略和时间同步，避免回放查询时出现空片段。',
        tags: ['NVR', '录像', '硬盘'],
      },
    ],
  },
]

